### ISSUE TITLE
Odd behaviour is server is left idle

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#925] opened 2015-04-06 19:08 UTC
Reported on mailing list.

My suspension is that the client side (emacs) is dropping an idle connection after a period (the exception in the log shows the server thinks the connection has been closed on it.

@aemoncannon  @edani  @fommil   Any thoughts about the emacs connection handling?

-----------

I'll move this to a new thread. I guess I'm not doing something I'm supposed to do or doing something I'm not, but I can't seem to track it down from looking at the Emacs plugin.

This is a section of my server log.

So type-at-point was working nicely, and then I leave the computer be for 3 hours. After that type-at-point gives bad answers and then I just close the socket from the client and run "init-project" again and then it works once more. Is there some kind of refresh I should make that I'm missing?
 
14:06:57.559 [Scala Presentation Compiler []] DEBUG o.e.core.RichPresentationCompiler - search: net.liftweb.record.MetaRecord = Some(FqnSymbol(Some(413951),file:///Users/viktor/.ivy2/cache/net.liftweb/lift-record_2.11/jars/lift-record_2.11-3.0-SNAPSHOT.jar,jar:file:///Users/viktor/.ivy2/cache/net.liftweb/lift-record_2.11/jars/lift-record_2.11-3.0-SNAPSHOT.jar!/net/liftweb/record/MetaRecord.class,net.liftweb.record.MetaRecord,None,None,Some(jar:file:///Users/viktor/.ivy2/cache/net.liftweb/lift-record_2.11/srcs/lift-record_2.11-3.0-SNAPSHOT-sources.jar!/net/liftweb/record/MetaRecord.scala),None,None))
14:06:57.581 [default-akka.actor.default-dispatcher-79] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "MetaRecord" :type-id 22 :decl-as trait :full-name "net.liftweb.record.MetaRecord" :type-args nil :members nil :pos (:type offset :file "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" :offset 1178) :outer-type-id nil)) 11)
17:06:51.410 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1234) 12)
17:06:51.918 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "<notype>" :type-id 1 :decl-as nil :full-name "<none>.<none>" :type-args nil :members nil :pos nil :outer-type-id nil)) 12)
17:07:06.763 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1192) 13)
17:07:06.764 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "<notype>" :type-id 1 :decl-as nil :full-name "<none>.<none>" :type-args nil :members nil :pos nil :outer-type-id nil)) 13)
17:07:45.313 [Thread-27] ERROR org.ensime.server.SocketReader - Error in socket reader:
java.io.EOFException: End of file reached in socket reader.
at org.ensime.server.protocol.swank.SwankWireFormatCodec$class.fillArray(SwankWireFormatCodec.scala:39) ~[swank_2.11.jar:0.9.10-SNAPSHOT]
at org.ensime.server.protocol.swank.SwankWireFormatCodec$class.readMessage(SwankWireFormatCodec.scala:49) ~[swank_2.11.jar:0.9.10-SNAPSHOT]
at org.ensime.server.protocol.swank.SwankProtocol.readMessage(SwankProtocol.scala:17) ~[swank_2.11.jar:0.9.10-SNAPSHOT]
at org.ensime.server.SocketReader.run(Server.scala:161) ~[server_2.11.jar:0.9.10-SNAPSHOT]
17:07:45.321 [default-akka.actor.default-dispatcher-95] ERROR org.ensime.server.SocketHandler - Socket closed, stopping self
17:07:45.324 [default-akka.actor.default-dispatcher-96] DEBUG org.ensime.server.SocketHandler - stopped
17:07:51.646 [Thread-16] INFO  org.ensime.server.Server - Got connection, creating handler...
17:07:51.650 [default-akka.actor.default-dispatcher-96] DEBUG org.ensime.server.SocketHandler - started (org.ensime.server.SocketHandler@5a215faa)
17:07:51.667 [default-akka.actor.default-dispatcher-96] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:init-project) 1)
17:07:51.668 [default-akka.actor.default-dispatcher-96] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok t) 1)
17:08:00.436 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1240) 2)
17:08:00.439 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "BaseRecord" :type-id 23 :decl-as nil :full-name "net.liftweb.record.BaseRecord" :type-args nil :members nil :pos (:type offset :file "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" :offset 1189) :outer-type-id nil)) 2)
17:08:05.747 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1282) 3)
17:08:05.750 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "FieldHolder" :type-id 25 :decl-as class :full-name "net.liftweb.record.MetaRecord$FieldHolder" :type-args nil :members nil :pos (:type offset :file "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" :offset 14458) :outer-type-id 24)) 3)
17:08:14.539 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/Record.scala" 1179) 4)
17:08:14.541 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "MetaRecord" :type-id 22 :decl-as trait :full-name "net.liftweb.record.MetaRecord" :type-args nil :members nil :pos (:type offset :file "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" :offset 1178) :outer-type-id nil)) 4)
17:08:16.267 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1237) 5)
17:08:16.269 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "BaseRecord" :type-id 23 :decl-as nil :full-name "net.liftweb.record.BaseRecord" :type-args nil :members nil :pos (:type offset :file "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" :offset 1189) :outer-type-id nil)) 5)
17:08:18.979 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1455) 6)

**Comment by aemoncannon** [comment] 2015-04-06 19:24
This is new to me.

**Comment by hedefalk** [comment] 2015-04-06 19:59
Sorry if I was unclear. The log is from using Atom as the client. The problem is that Ensime server answers "badly" with:
```
17:06:51.410 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1234) 12)
17:06:51.918 [default-akka.actor.default-dispatcher-38] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "<notype>" :type-id 1 :decl-as nil :full-name "<none>.<none>" :type-args nil :members nil :pos nil :outer-type-id nil)) 12)
```

Then I just closed the connection from Atom and started a new session against the same server and then everything is a-ok again.

```
17:08:00.436 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" 1240) 2)
17:08:00.439 [default-akka.actor.default-dispatcher-97] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "BaseRecord" :type-id 23 :decl-as nil :full-name "net.liftweb.record.BaseRecord" :type-args nil :members nil :pos (:type offset :file "/Users/viktor/dev/projects/kostbevakningen/.ensime_cache/dep-src/source-jars/net/liftweb/record/MetaRecord.scala" :offset 1189) :outer-type-id nil)) 2)
```

The closed connection is just me reloading in Atom.

**Comment by hedefalk** [comment] 2015-04-06 20:00
Please let me know if it helps with a cleaner example. The log was a bit bloated, I could probably isolate a bit further.

**Comment by rorygraves** [comment] 2015-04-06 20:21
@hedefalk  whoops - my inept reading of your log.  Have updated the title.

**Comment by hedefalk** [comment] 2015-04-08 11:20
Weird, but things have seemed to improve a lot. I haven't had this problem for a while now and have continued working with Atom. Maybe I did something über-weird from the client, dunno. Maybe should close this for now. The log above did happen though…

**Comment by hedefalk** [comment] 2015-04-09 15:48
I still get some of these though, but it doesn't seem related to long idle times:

```
17:44:22.005 [default-akka.actor.default-dispatcher-8] INFO  o.e.s.protocol.swank.SwankProtocol - Received msg: (:swank-rpc (swank:type-at-point "/Users/viktor/dev/projects/kostbevakningen/src/main/scala/se/kostbevakningen/snippet/EditIngredient.scala" 1489) 7)
17:44:22.007 [default-akka.actor.default-dispatcher-8] INFO  o.e.s.protocol.swank.SwankProtocol - Writing: (:return (:ok (:arrow-type nil :name "<notype>" :type-id 1 :decl-as nil :full-name "<none>.<none>" :type-args nil :members nil :pos nil :outer-type-id nil)) 7)
````

**Comment by fommil** [comment] 2015-08-17 19:47
we've not seen this in some time, reopen if you still see it.

**Closed by fommil** 2015-08-17 19:47 UTC
