### ISSUE TITLE
symbol search not returning correct line numbers

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1140] opened 2015-11-04 14:08 UTC
_From @caente on November 4, 2015 12:56_

When I search for a symbol, it takes me to the file, but not to the symbol, is this known?

**Comment by hedefalk** [comment] 2015-11-04 14:08
This is a pretty new feature in Atom and I haven't used it much yet - will tomorrow though. It _should_ work client wise and it worked half ok for me (one-off errors kindof). I'll blame server. Please check server communication and see what you get there. (cmd-shift-i on mac to open chrome dev tools in atom). What you get is only line-positions so not col, but for me it has at least done better than just open the file.

What I noticed though is that my own files hasn't been indexed properly. There's work going on to make all that stuff better in ensime-server though…

**Comment by hedefalk** [comment] 2015-11-04 14:08
_From @caente on November 4, 2015 13:59_

well this interesting, it actually receives back two objects, the first one has a `pos.line > 0`, but the line number is wrong, the second one has `pos.line=0`
I guess those two objects are the the two elements I see in the search box when I write the name of the method I'm looking for, one is something like `SomeModule$.someMethod` -> this one has the wrong line number, and the other result is `SomeModule.someMethod` -> this one has the line number as 0

do let me know if there is anything else I can do to debug this further, this is one of the features I missed the most (I'm  currently using ctags for symbol navigation)

**Comment by hedefalk** [comment] 2015-11-04 14:08
Yeah, this is an important feature for me too. I'm going to move this issue to ensime-server (because ensime-atom just puts the cursor on the line given from server (maybe with an off-by-one error (I'll look at that tomorrow)))

Can you paste the full json you get? Better still if you can isolate the issue in a standalone git project…

**Comment by fommil** [comment] 2015-11-04 14:17
this is actually missing information in the binary files, typically the scala library class files don't include this information. Try it on something in your own classpath, and something from a java third party library.

There might be an open ticket for this actually, as the workaround is to load the target file in the presentation compiler, work out the line number, and then send that on to the requester... but that means that every search hit incurs this side effect which is really harsh. So maybe the search protocol should be lazy allowing for additional information on individual entries.

**Comment by fommil** [comment] 2015-11-05 08:01
Actually sounds like the reporter is looking for a method on a trait which at the byte level is going to be on a companion.

**Comment by hedefalk** [comment] 2015-11-05 08:05
Ping @caente in case you don't get updates.

**Comment by fommil** [comment] 2015-11-05 08:08
To be honest I can't really look out this until the new year, I've got too many commitments. This code in currently being rewritten but I doubt it will fixed in this update because fundamentally the indexer is JVM indexing not Scala indexing. Somebody could implement a workaround however.

**Comment by hedefalk** [comment] 2015-11-05 08:14
Fair enough. No pressure, maaan!

Yeah, and workaround now that just adds to what has to be rewritten in the "big graphocalypse" probably doesn't make much sense either?

**Comment by caente** [comment] 2015-11-05 14:16
@fommil for what is worth, there was no trait involved this is the only source code in the project:
```
object module {
  def someMethod(f: String):Int = f.toInt
}
```

**Comment by fommil** [comment] 2016-04-15 20:15
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.

**Closed** 2016-04-29 18:28 UTC
Labels: Indexer, Needs Reproduction
