### ISSUE TITLE
Automatic imports

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1425] opened 2016-04-19 12:52 UTC
If a code completion is for a symbol not in scope, it'd be nice to get a patch for a top level import.

https://github.com/ensime/ensime-atom/issues/181

**Comment by fommil** [comment] 2016-04-19 13:15
@aemoncannon didn't you say this was a game changer for IDEA when you used it a while ago?

**Comment by fommil** [comment] 2016-04-19 13:17
it's possible that this should be implemented client-side, given that the choice of a completion is such an interactive thing. But it would perhaps be good if the FQN (or diff) was provided (only iff it is needed) to enable this.

**Comment by aemoncannon** [comment] 2016-04-19 14:26
It is a super nice feature. I think this falls into this falls into the
'fixup' family of features. Kind of a UI challenge in emacs...

**Comment by fommil** [comment] 2016-04-19 14:27
#848

**Comment by hedefalk** [comment] 2016-04-19 18:04
Yeah, I was definitely thinking of client side application, all refactorings are patches + client side application already?

I just mean that when server provides a completion that depends on an imported symbol, it would be nice if we could just piggy back any needed FQN toplevel import as a patch too… Or maybe just the name, but that it's simple to then ask for the import patch. I mean, server knows this when it gives the completion…

**Comment by hedefalk** [comment] 2016-04-19 18:21
Hm, but maybe the default that All IDE's does, to import to top level isn't necessarily the only way a client might want to have it… A patch nails where the import goes, so maybe not really bullet proof to provide a patch. Maybe client want to have a setting to instead to put the import just above the inserted completion, dunno…?

**Comment by fommil** [comment] 2016-12-21 16:45
depends on https://github.com/ensime/ensime-server/issues/1401 ?

**Comment by fommil** [comment] 2017-07-26 20:10
hold on, isn't this just a dupe of #1401 ? I was talking to @VC1995 about this one... yes it'd be good. I think there was an upstream bug but maybe we could just implement a hack. If we can write it in Emacs Lisp we can write it in Scala!

**Closed by fommil** 2017-07-26 20:10 UTC
