### ISSUE TITLE
Auto-completion in the REPL

### ISSUE THREAD

**Issue by codekingplusplus** [ensime/ensime-server#521] opened 2014-07-19 02:48 UTC
I can get auto-complete to work in a buffer that is connected to an ensime-server however, this does not appear to be the case with the REPL. In fact, when I attempt to connect to ensime from the REPL I get the following error: "Asynchronous RPC aborted: actor name [indexer] is not unique!"

How can I achieve auto-completion in the REPL? 
Is it even possible to connect to the Ensime Server from the REPL?

**Comment by fommil** [comment] 2015-08-28 08:09
dupe of #988

**Closed by fommil** 2015-08-28 08:09 UTC
