### ISSUE TITLE
Infinite recursion in protocol

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-server#840] opened 2015-02-24 05:35 UTC
23:32:50.583 [default-akka.actor.default-dispatcher-4] ERROR akka.actor.ActorSystemImpl - Uncaught fatal error from thread [default-akka.actor.default-dispatcher-3] shutting down ActorSystem [default]
java.lang.StackOverflowError: null
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.SexpList$.rec$1(Sexp.scala:68) ~[ensime_2.11.jar:0.9.10-SNAPSHOT]

**Comment by fommil** [comment] 2015-02-24 08:55
What was the input string? Might just be a really big s-expression.

**Comment by fommil** [comment] 2015-02-24 08:57
dupe of #692 (but seeing the input string would be good for testing)

**Closed by fommil** 2015-02-24 08:57 UTC
