### ISSUE TITLE
Missing inference type for by name parameters

### ISSUE THREAD

**Issue by jvican** [ensime/ensime-server#1215] opened 2016-01-09 18:19 UTC
When checking the type param of the function `startServer` in `spray`, I get this response:
```
2016-01-09 18:42:10.776318: unqueue: result received {
  "callId": 3,
  "payload": {
    "resultType": {
      "name": "Future",
      "fullName": "scala.concurrent.Future",
      "typehint": "BasicTypeInfo",
      "typeId": 357,
      "typeArgs": [{
        "name": "Bound",
        "fullName": "akka.io.Tcp$$Bound",
        "typehint": "BasicTypeInfo",
        "typeId": 359,
        "outerTypeId": 358,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }],
      "members": [],
      "declAs": {
        "typehint": "Trait"
      }
    },
    "name": "(interface: String, port: Int, serviceActorName: String, backlog: Int, options: scala.collection.immutable.Traversable[akka.io.Inet.SocketOption], settings: Option[spray.can.server.ServerSettings])(route: => spray.routing.Route)(implicit system: akka.actor.ActorSystem, implicit sslEngineProvider: spray.io.ServerSSLEngineProvider, implicit bindingTimeout: akka.util.Timeout)scala.concurrent.Future[spray.can.Http.Bound]",
    "paramSections": [{
      "params": [["interface", {
        "name": "String",
        "fullName": "java.lang.String",
        "typehint": "BasicTypeInfo",
        "typeId": 58,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }], ["port", {
        "name": "Int",
        "fullName": "scala.Int",
        "typehint": "BasicTypeInfo",
        "typeId": 346,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }], ["serviceActorName", {
        "name": "String",
        "fullName": "java.lang.String",
        "typehint": "BasicTypeInfo",
        "typeId": 58,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }], ["backlog", {
        "name": "Int",
        "fullName": "scala.Int",
        "typehint": "BasicTypeInfo",
        "typeId": 346,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }], ["options", {
        "name": "Traversable",
        "fullName": "scala.collection.immutable.Traversable",
        "typehint": "BasicTypeInfo",
        "typeId": 347,
        "typeArgs": [{
          "name": "SocketOption",
          "fullName": "akka.io.Inet$$SocketOption",
          "typehint": "BasicTypeInfo",
          "typeId": 349,
          "outerTypeId": 348,
          "typeArgs": [],
          "members": [],
          "declAs": {
            "typehint": "Trait"
          }
        }],
        "members": [],
        "declAs": {
          "typehint": "Trait"
        }
      }], ["settings", {
        "name": "Option",
        "fullName": "scala.Option",
        "typehint": "BasicTypeInfo",
        "typeId": 350,
        "typeArgs": [{
          "name": "ServerSettings",
          "fullName": "spray.can.server.ServerSettings",
          "typehint": "BasicTypeInfo",
          "typeId": 351,
          "typeArgs": [],
          "members": [],
          "declAs": {
            "typehint": "Class"
          }
        }],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }]],
      "isImplicit": false
    }, {
      "params": [["route", {
        "name": "<byname>",
        "fullName": "scala.<byname>",
        "typehint": "BasicTypeInfo",
        "typeId": 352,
        "typeArgs": [{
          "name": "Function1",
          "fullName": "scala.Function1",
          "typehint": "BasicTypeInfo",
          "typeId": 11,
          "typeArgs": [],
          "members": [],
          "declAs": {
            "typehint": "Trait"
          }
        }],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }]],
      "isImplicit": false
    }, {
      "params": [["system", {
        "name": "ActorSystem",
        "fullName": "akka.actor.ActorSystem",
        "typehint": "BasicTypeInfo",
        "typeId": 353,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }], ["sslEngineProvider", {
        "name": "ServerSSLEngineProvider",
        "fullName": "spray.io.ServerSSLEngineProvider",
        "typehint": "BasicTypeInfo",
        "typeId": 354,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Trait"
        }
      }], ["bindingTimeout", {
        "name": "Timeout",
        "fullName": "akka.util.Timeout",
        "typehint": "BasicTypeInfo",
        "typeId": 355,
        "typeArgs": [],
        "members": [],
        "declAs": {
          "typehint": "Class"
        }
      }]],
      "isImplicit": true
    }],
    "typehint": "ArrowTypeInfo",
    "typeId": 356
  }
}
```
As you see, the second list of parameters of the function has the type `<byname>` when it should have the type `spray.routing.Route`. However, the `name` field gives the right type.

**Comment by fommil** [comment] 2016-01-09 18:28
can you provide the example project that created this? It's usually more interesting than the result.

**Comment by jvican** [comment] 2016-01-09 18:29
```
(
 :root-dir "/data/rw/code/scala/phonebook-server"
 :cache-dir "/data/rw/code/scala/phonebook-server/.ensime_cache"
 :name "phonebook-server"
 :java-home "/etc/java-config-2/current-system-vm"
 :java-flags ("-XX:MaxPermSize=256m" "-XX:ReservedCodeCacheSize=128m" "-Xms1024m" "-Xmx1024m" "-Xss2m")
 :reference-source-roots ("/etc/java-config-2/current-system-vm/src.zip")
 :scala-version "2.11.7"
 :compiler-args ("-Xfuture" "-Xlint" "-Yinline-warnings" "-Yno-adapted-args" "-Ywarn-dead-code" "-Ywarn-numeric-widen" "-Ywarn-unused-import" "-deprecation" "-feature")
 :formatting-prefs nil
 :subprojects ((
   :name "phonebook-server"
   :source-roots ("/data/rw/code/scala/phonebook-server/src/main/scala" "/data/rw/code/scala/phonebook-server/src/test/scala")
   :targets ("/data/rw/code/scala/phonebook-server/target/scala-2.11/classes")
   :test-targets ("/data/rw/code/scala/phonebook-server/target/scala-2.11/test-classes")
   :depends-on-modules nil
   :compile-deps ("/home/jvican/.ivy2/cache/com.chuusai/shapeless_2.11/jars/shapeless_2.11-1.2.4.jar" "/home/jvican/.ivy2/cache/com.h2database/h2/jars/h2-1.3.170.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/jars/akka-actor_2.11-2.3.9.jar" "/home/jvican/.ivy2/cache/com.typesafe.slick/slick_2.11/bundles/slick_2.11-3.1.0.jar" "/home/jvican/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar" "/home/jvican/.ivy2/cache/io.spray/spray-can_2.11/bundles/spray-can_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-http_2.11/bundles/spray-http_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-httpx_2.11/bundles/spray-httpx_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-io_2.11/bundles/spray-io_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-json_2.11/bundles/spray-json_2.11-1.3.2.jar" "/home/jvican/.ivy2/cache/io.spray/spray-routing_2.11/bundles/spray-routing_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/io.spray/spray-util_2.11/bundles/spray-util_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/org.jvnet.mimepull/mimepull/jars/mimepull-1.9.5.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-core/jars/parboiled-core-1.1.7.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-scala_2.11/jars/parboiled-scala_2.11-1.1.7.jar" "/home/jvican/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.3.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.10.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-nop/jars/slf4j-nop-1.6.4.jar")
   :runtime-deps nil
   :test-deps ("/home/jvican/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/jars/akka-testkit_2.11-2.3.9.jar" "/home/jvican/.ivy2/cache/io.spray/spray-testkit_2.11/jars/spray-testkit_2.11-1.3.3.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.2.jar" "/home/jvican/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar" "/home/jvican/.ivy2/cache/org.scalacheck/scalacheck_2.11/jars/scalacheck_2.11-1.12.5.jar" "/home/jvican/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-2.2.4.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/bundles/scalaz-concurrent_2.11-7.0.6.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.0.6.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-effect_2.11/bundles/scalaz-effect_2.11-7.0.6.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-common_2.11/jars/specs2-common_2.11-2.3.11.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-core_2.11/jars/specs2-core_2.11-2.3.11.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-matcher_2.11/jars/specs2-matcher_2.11-2.3.11.jar")
   :doc-jars ("/data/rw/code/scala/phonebook-server/target/scala-2.11/agenda-server_2.11-1.0-javadoc.jar" "/home/jvican/.ivy2/cache/com.chuusai/shapeless_2.11/docs/shapeless_2.11-1.2.4-javadoc.jar" "/home/jvican/.ivy2/cache/com.h2database/h2/docs/h2-1.3.170-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/docs/akka-actor_2.11-2.3.9-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/docs/akka-testkit_2.11-2.3.9-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe.slick/slick_2.11/docs/slick_2.11-3.1.0-javadoc.jar" "/home/jvican/.ivy2/cache/com.typesafe/config/docs/config-1.2.1-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-can_2.11/docs/spray-can_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-http_2.11/docs/spray-http_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-httpx_2.11/docs/spray-httpx_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-io_2.11/docs/spray-io_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-json_2.11/docs/spray-json_2.11-1.3.2-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-routing_2.11/docs/spray-routing_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-testkit_2.11/docs/spray-testkit_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/io.spray/spray-util_2.11/docs/spray-util_2.11-1.3.3-javadoc.jar" "/home/jvican/.ivy2/cache/org.jvnet.mimepull/mimepull/docs/mimepull-1.9.5-javadoc.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-core/docs/parboiled-core-1.1.7-javadoc.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-scala_2.11/docs/parboiled-scala_2.11-1.1.7-javadoc.jar" "/home/jvican/.ivy2/cache/org.reactivestreams/reactive-streams/docs/reactive-streams-1.0.0-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/docs/scala-parser-combinators_2.11-1.0.1-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/docs/scala-xml_2.11-1.0.3-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.7-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-reflect/docs/scala-reflect-2.11.2-javadoc.jar" "/home/jvican/.ivy2/cache/org.scala-sbt/test-interface/docs/test-interface-1.0-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalacheck/scalacheck_2.11/docs/scalacheck_2.11-1.12.5-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalatest/scalatest_2.11/docs/scalatest_2.11-2.2.4-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/docs/scalaz-concurrent_2.11-7.0.6-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-core_2.11/docs/scalaz-core_2.11-7.0.6-javadoc.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-effect_2.11/docs/scalaz-effect_2.11-7.0.6-javadoc.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-api/docs/slf4j-api-1.7.10-javadoc.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-nop/docs/slf4j-nop-1.6.4-javadoc.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-common_2.11/docs/specs2-common_2.11-2.3.11-javadoc.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-core_2.11/docs/specs2-core_2.11-2.3.11-javadoc.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-matcher_2.11/docs/specs2-matcher_2.11-2.3.11-javadoc.jar")
   :reference-source-roots ("/home/jvican/.ivy2/cache/com.chuusai/shapeless_2.11/srcs/shapeless_2.11-1.2.4-sources.jar" "/home/jvican/.ivy2/cache/com.h2database/h2/srcs/h2-1.3.170-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-actor_2.11/srcs/akka-actor_2.11-2.3.9-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe.akka/akka-testkit_2.11/srcs/akka-testkit_2.11-2.3.9-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe.slick/slick_2.11/srcs/slick_2.11-3.1.0-sources.jar" "/home/jvican/.ivy2/cache/com.typesafe/config/srcs/config-1.2.1-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-can_2.11/srcs/spray-can_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-http_2.11/srcs/spray-http_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-httpx_2.11/srcs/spray-httpx_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-io_2.11/srcs/spray-io_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-json_2.11/srcs/spray-json_2.11-1.3.2-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-routing_2.11/srcs/spray-routing_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-testkit_2.11/srcs/spray-testkit_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/io.spray/spray-util_2.11/srcs/spray-util_2.11-1.3.3-sources.jar" "/home/jvican/.ivy2/cache/org.jvnet.mimepull/mimepull/srcs/mimepull-1.9.5-sources.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-core/srcs/parboiled-core-1.1.7-sources.jar" "/home/jvican/.ivy2/cache/org.parboiled/parboiled-scala_2.11/srcs/parboiled-scala_2.11-1.1.7-sources.jar" "/home/jvican/.ivy2/cache/org.reactivestreams/reactive-streams/srcs/reactive-streams-1.0.0-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/srcs/scala-parser-combinators_2.11-1.0.1-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/srcs/scala-xml_2.11-1.0.3-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.7-sources.jar" "/home/jvican/.ivy2/cache/org.scala-lang/scala-reflect/srcs/scala-reflect-2.11.2-sources.jar" "/home/jvican/.ivy2/cache/org.scala-sbt/test-interface/srcs/test-interface-1.0-sources.jar" "/home/jvican/.ivy2/cache/org.scalacheck/scalacheck_2.11/srcs/scalacheck_2.11-1.12.5-sources.jar" "/home/jvican/.ivy2/cache/org.scalatest/scalatest_2.11/srcs/scalatest_2.11-2.2.4-sources.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-concurrent_2.11/srcs/scalaz-concurrent_2.11-7.0.6-sources.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-core_2.11/srcs/scalaz-core_2.11-7.0.6-sources.jar" "/home/jvican/.ivy2/cache/org.scalaz/scalaz-effect_2.11/srcs/scalaz-effect_2.11-7.0.6-sources.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-api/srcs/slf4j-api-1.7.10-sources.jar" "/home/jvican/.ivy2/cache/org.slf4j/slf4j-nop/srcs/slf4j-nop-1.6.4-sources.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-common_2.11/srcs/specs2-common_2.11-2.3.11-sources.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-core_2.11/srcs/specs2-core_2.11-2.3.11-sources.jar" "/home/jvican/.ivy2/cache/org.specs2/specs2-matcher_2.11/srcs/specs2-matcher_2.11-2.3.11-sources.jar")))
)
```

**Comment by fommil** [comment] 2016-01-09 18:29
no, I mean the project itself. The source code that triggered it. Everything else is kind of irrelevant compared to the source code that produced this.

**Comment by jvican** [comment] 2016-01-09 18:32
Oh, sorry. Do you want to check the whole project or only the main class?
Main class [here](https://gist.github.com/jvican/7802cd14791261485930). Whole project will be more difficult, it's private, but if you really need it I could make it public.

**Comment by fommil** [comment] 2016-01-09 18:33
yes, please copy that source here. It's the most important bit.

**Comment by jvican** [comment] 2016-01-09 18:34
```scala

package server

import akka.actor.{ActorSystem, Props}
import akka.io.IO
import akka.pattern.ask
import akka.util.Timeout
import spray.can.Http

import spray.routing.SimpleRoutingApp
import db.PhonebookDB
import core.ServerCore
import api.PhonebookApi

import scala.concurrent.ExecutionContext

object Server extends App
                 with SimpleRoutingApp 
                 with PhonebookDB 
                 with PhonebookApi 
                 with ServerCore {

  log.info("Starting `Phonebook` service...")
  startServer(interface = "localhost", port = 8080) {
    routes
  }

  override implicit val ec: ExecutionContext =
    actorRefFactory.dispatcher

  initDatabase
}
```

**Comment by fommil** [comment] 2016-01-09 18:37
I can imagine what's happening here. I have had to implement some workarounds for by-name parameters in the FQN calculations.

**Comment by jvican** [comment] 2016-01-09 18:39
Great! When are you guys releasing the next version? (aprox)

**Comment by fommil** [comment] 2016-01-09 18:42
every commit that is merged is released, but my personal backlog is so big I don't think I'll get around to this anytime soon. Maybe somebody can pick it up at the hack day, unless you're interested?

**Comment by jvican** [comment] 2016-01-09 18:45
Count me in, I will take it but give me some time as well as I will be busy the next week.

**Comment by fommil** [comment] 2016-04-15 20:16
We're going through the older bug reports that don't have a reproduction.

Nowadays, we close tickets that look like a known issue or don't provide the details requested by the template (which didn't exist when you reported this). The reason is to improve the quality of our issue tracker and to make it easier for contributors to help.

Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. We are happy to help you write an automated test exhibiting the bug, and discuss ideas on how to fix, read the http://ensime.org/contributing guide for more information.

We will leave this ticket open for a few weeks. If you can confirm it is a bug by giving us a **detailed** reproduction - or let us know that you're working on a fix - we will leave it open for longer.

Please read the http://ensime.org/getting_help guide to understand the steps that are now required prior to submitting a bug report. We recently rewrote almost all the documentation since this bug was initially reported and you might find some useful information in there.

**Closed** 2016-04-29 18:28 UTC
Labels: Analyser, Bug, Low Hanging Fruit, Needs Reproduction
