### ISSUE TITLE
Parse error causes Ensime server exit in sexp

### ISSUE THREAD

**Issue by dickwall** [ensime/ensime-server#1243] opened 2016-01-22 22:50 UTC
As discussed on gitter, new parser impl breaks on the following, and exits ensime during regular use:

```
[Ensime] 2016-01-22 14:37:29,712 [INFO ]  EnsimeInspectTypeStatus.handleReply: {'outer_type_id': False, 'members': [], 'type_id': 3, 'arrow_type': False, 'name': 'Boolean', 'type_args': [], 'full_name': 'scala.Boolean', 'decl_pos': <Ensime.rpc.SourcePosition object at 0x7fbc0b8f9290>, 'decl_as': class}
[Ensime] 2016-01-22 14:37:34,914 [INFO ]  request #7(sync) send - b'(:swank-rpc (swank:completions (:file "/home/dick/dev/VineSleuth/wine4me-api/app/vinesleuth/dbaccess'...
[Ensime] 2016-01-22 14:37:35,915 [WARNI]  sync_req #7 has timed out (didn't get a response after 1.0 seconds)
[Ensime] 2016-01-22 14:37:34,950 [INFO ]  Server: OUT: b'14:37:34.950 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection\njava.lang.Exception: Failed to parse sexp: Invalid input \'\\n\', expected Character or \'"\' (line 1, column 159):\n(:swank-rpc (swank:completions (:file "/home/dick/dev/VineSleuth/wine4me-api/app/vinesleuth/dbaccess/UsersAccess.scala" :contents "package vinesleuth.dbaccess\n                                                                                                                                                              ^\n\n3 rules mismatched at error location:\n  ...:-128 /SexpP/ |:-127 /SexpListP/ *:-121 /SexpP/ |:-28 /SexpAtomP/ |:-28 /SexpStringP/ *:-27 /Character/ | /EscapedChar/ \'\\\'\n  ...xpListP/ *:-121 /SexpP/ |:-28 /SexpAtomP/ |:-28 /SexpStringP/ *:-27 /Character/ | /NormalChar/ capture / --:<CharPredicate>\n  ...:-147 /SexpP/ |:-146 /SexpListP/ *:-128 /SexpP/ |:-127 /SexpListP/ *:-121 /SexpP/ |:-28 /SexpAtomP/ |:-28 /SexpStringP/ \'"\'\n\n\tat org.ensime.sexp.SexpParser$.parse(SexpParser.scala:20) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat org.ensime.sexp.PimpedString.parseSexp(package.scala:17) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat org.ensime.server.SwankProtocol.decode(SwankProtocol.scala:14) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat org.ensime.server.tcp.TCPConnectionActor.repeatedDecode(TCPConnectionActor.scala:106) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat org.ensime.server.tcp.TCPConnectionActor.attemptProcess(TCPConnectionActor.scala:95) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat org.ensime.server.tcp.TCPConnectionActor$$anonfun$incoming$1.applyOrElse(TCPConnectionActor.scala:47) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.7.jar:na]\n\tat akka.actor.Actor$class.aroundReceive(Actor.scala:467) ~[akka-actor_2.11-2.3.14.jar:na]\n\tat org.ensime.server.tcp.TCPConnectionActor.aroundReceive(TCPConnectionActor.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.14.jar:na]\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.14.jar:na]\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.14.jar:na]\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.14.jar:na]\n\tat akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397) [akka-actor_2.11-2.3.14.jar:na]\n\tat scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.7.jar:na]\n\tat scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.7.jar:na]\n\tat scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.7.jar:na]\n\tat scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.7.jar:na]\n'
[Ensime] 2016-01-22 14:37:34,955 [INFO ]  Server: OUT: b'14:37:34.955 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/2 a.i.SelectionHandler - Monitored actor [Actor[akka://ENSIME/user/ensime-main/tcp-server/con1#884824983]] terminated\n'
[Ensime] 2016-01-22 14:37:34,955 [ERROR]  *****    ERROR     *****
[Ensime] 2016-01-22 14:37:34,957 [ERROR]  Traceback (most recent call last):
  File "/home/dick/.config/sublime-text-3/Packages/Ensime/ensime.py", line 376, in receive_loop
    msglen = self.socket.recv(6)
ConnectionResetError: [Errno 104] Connection reset by peer

Controller shutdown() called
shutdown() called
```

**Comment by fommil** [comment] 2016-01-22 23:53
fixed now, but needs a permanent fix in the parboiled2 parser branch

**Comment by fommil** [comment] 2016-01-26 23:27
I simply cannot reproduce this. I've tried adding newlines, reproducing the exact payload, it is passing. I think I'd need to see the raw payload before having a clue what's going on. My guess is that this is a bug in the sublime s-exp generator.

**Comment by fommil** [comment] 2016-01-26 23:33
@dickwall the performance of the SWANK protocol to handle full messages is terrible, so the other clients have moved to sending the variant with the unsaved file in a temporary file. Would it be much work to fix up sublime to do that? The best I can guess here is that it's some kind of encoding problem. Was it very repeatable?

**Comment by fommil** [comment] 2016-01-26 23:44
I wish the `request #7` line wasn't truncated! What's the `b` at the start?

**Comment by fommil** [comment] 2016-01-27 00:31
@dickwall I went through this with @magnusart and we couldn't reproduce using my dev branch.

Can you please `publishLocal` my branch https://github.com/fommil/ensime-server/tree/parboiled2 and see if you can reproduce. If you could capture the exact source file, and get a dump of the outgoing payload (without the extra escaping that python adds) that'd be great. If you can't reproduce, then we'll have to call this a false alarm in the first place.

**Comment by fommil** [comment] 2016-01-27 00:37
btw, I raised https://github.com/ensime/ensime-sublime/issues/97 now that I know that you're not using the tmp file approach to communicate with the server.

**Closed** 2016-01-27 22:53 UTC
Labels: Needs More Info
