### ISSUE TITLE
EnsimeServer becomes unresponsive for search-related queries if many files change and compiler is invoked

### ISSUE THREAD

**Issue by timcharper** [ensime/ensime-server#1772] opened 2017-05-06 00:17 UTC
Continuation of #1770

Video recording:

https://www.youtube.com/watch?v=vf5YKqQlC3E

Action starts at about 3:30. The rest shows a fresh clone, compile, setup, etc. Video has been edited to reduce length.

### Steps to reproduce

1. clone git@github.com:timcharper/marathon.git
1. `git checkout tharper/akka-http-apps-controller-ensime-bug`
1. `sbt test:compile ensimeConfig ensimeServerIndex`
1. Open `./src/main/scala/mesosphere/marathon/api/akkahttp/v2/AppsController.scala` in emacs
1. Launch ensime (`m-x ensime`)
1. Wait for ensime to launch
1. Type `Try` in the top of some method, and use `C-c C-r t`, verify that it imports properly
1. Undo all changes to the file
1. Back in terminal: `git checkout tharper/akka-http-apps-controller-ensime-bug-2`
1. Now run `sbt test:compile`
1. As the compilation is running, notice in the ensime connection log the following message is repeated very often (multiple times per millisecond):

        17:27:49.264 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message AskReTypecheck from Actor[akka://ENSIME/user/ensime-main/project#548004105] in state handleRequests

1. When compilation finishes, notice that typechecking still works. Make some invalid change to the file, watch it go red; undo, watch it go green again.
1. Type `Try` again in the top of some method, and try to import the symbol with `C-c C-r t`
1. Emacs becomes unresponsive because ensime does not respond with import suggestions

I think the main culprit is the `AskReTypecheck infinite loop` we get in to. I've seen this happen pretty often and think many of the freeze-up issues I am seeing are due to it.

### Other notes

I have 4gb of ram for my ensime process. At no point does it come close to exceeding that when the issue manifests (watching via VisualVM). This can be seen in the video. The issue does not appear to be heap size related in any sense.

**Comment by timcharper** [comment] 2017-05-06 02:44
I encounter this same issue without switching branches; it seems like running the compiler, at all, while developing, _can_ cause it (but doesn't always).

The above repro solution, however, causes the issue always.

**Comment by iravid** [comment] 2017-05-06 06:15
It's actually not an infinite loop, just a long one :-) the file watcher asks for a retype check whenever one of the classes change in the target folder, so checkouts or big compile cycles cause a large flood of type check requests.

There's a WIP PR for denouncing those requests if I am not mistaken.

________________________________

**Comment by iravid** [comment] 2017-05-06 06:15
(To clarify - I noticed this issue as well)

________________________________

**Comment by fommil** [comment] 2017-05-06 08:28
I think this is a dupe of #1758

**Comment by fommil** [comment] 2017-05-06 08:29
Workaround is to drop back to -M1 until somebody makes this go faster. It should be on the Sponsored backlog but I'm not sure if that guarantees success... I think we need to replace OrientDB with a custom backend to be honest.

**Comment by timcharper** [comment] 2017-05-06 18:16
@fommil are you sure?

I can trigger this issue just compiling a single file, sometimes. This message gets output several times per millisecond:

```
 17:27:49.264 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message AskReTypecheck from Actor[akka://ENSIME/user/ensime-main/project#548004105] in state handleRequests
```

It feels like an infinite loop, to me.

I've waited for quite some time when the condition began. It _NEVER_ finishes. Also... we probably should not be logging at that rate, either way.

**Comment by gaydenko** [comment] 2017-05-06 18:45
BTW, I have noticed something similar a couple of times (I mean ENSIME buffer few dozens MB with similar messages) and emacs daemon eating (sit down, please) 20GB of RAM.

**Comment by fommil** [comment] 2017-05-06 21:12
Retypecheck happens every time a file is modified. But we debounce it. Take a visualvm/yourkit CPU profile when then happens, I bet all the time is in orientdb IO.

**Comment by fommil** [comment] 2017-05-06 21:13
Does M1 have the same problem?

**Comment by timcharper** [comment] 2017-05-07 16:01
If RetypeCheck happens every time a file is modified, and it is debounced, then debouncing is not working.

Strangely, **vast** majority of the time is in:

- `ForkJoinPool.scan`
- `logback.core.joran.ConsoleTarget`
- `forkjoin.ForkJoinPool.idleAwaitWork`

I have the CPU sampler open at 4:14 in my video: https://youtu.be/vf5YKqQlC3E?t=4m14s

This is explained by two things:

- logback is consuming a lot of resources because we are logging an insane amount of messages. Probably about 10,000/sec. Also, it is writing to an emacs buffer, which starts to block
- Large amount of CPU in `ForkJoinPool` scan / idleAwaitWork happens when you overload the ForkJoin scheduler with a million, concurrent, tiny tasks. 

Also, we have a lot `LightArrayResolverScheduler.wait`, which, if I were to wager a guess, is our attempt at debouncing. (lots of `scheduler.scheduleOnce` messages).

OrientDB is using some CPU, but, in total I'd say it's about 4-5% of the total CPU load. The Lucene index writer is using about 4-5% of the total CPU load, also.

I can try to use M1.

**Comment by timcharper** [comment] 2017-05-07 18:05
The same problem occurs with `2.0.0-M1`.

**Comment by timcharper** [comment] 2017-05-07 18:09
(Sorry - I originally reported they have the same problem, but, they only both exhibit the same symptom in which they `AskReTypecheck` forever.)

---

`2.0.0-M1` DOES NOT lock up when trying to import after the repro case. However, it does log, indefinitely, the log message for `AskReTypecheck`.

**Comment by timcharper** [comment] 2017-05-08 03:54
Since there are two separate issues here, I've created a new one for the `AskRetypeCheck` log message flood, ^

**Comment by fommil** [comment] 2017-05-20 16:34
@timcharper did you fix this or is it still open?

**Comment by fommil** [comment] 2017-05-20 16:35
I think you fixed it given all the commits :smile:

**Closed by fommil** 2017-05-20 16:35 UTC
