### ISSUE TITLE
build should pass with stock sbt launcher script

### ISSUE THREAD

**Issue by markschaake** [ensime/ensime-server#1064] opened 2015-08-17 13:52 UTC
I just pulled the latest and ran the tests. Jerk tests failed:

```shell
> jerk/test
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] JerkFormatsSpec:
[info] Jerk Formats
[info] - should roundtrip request envelopes
[info] - should roundtrip RPC response envelopes
[info] Exception encountered when attempting to run a suite with class name: org.ensime.jerk.JerkFormatsSpec *** ABORTED ***
[info]   java.lang.StackOverflowError:
[info]   at org.ensime.jerk.JerkConversions$fresh$macro$1613$1.inst$macro$1610(JerkFormats.scala:41)
[info]   at org.ensime.jerk.JerkConversions$fresh$macro$1613$1.inst$macro$1610$lzycompute(JerkFormats.scala:41)
[info]   at org.ensime.jerk.JerkConversions$fresh$macro$1613$1.inst$macro$1610(JerkFormats.scala:41)
...
```

Here's the perma-link to the source that is failing: https://github.com/ensime/ensime-server/blob/e34e4935c98533ee3c9a3a804650883a7d9bdd9c/jerk/src/main/scala/org/ensime/jerk/JerkFormats.scala#L41

Update (see comments below): this failure occurred for me because I was using the stock SBT launcher script whereas the Ensime project is built using paulp's [alternative script](https://github.com/paulp/sbt-extras). I've renamed the issue to reflect my opinion that Ensime's build should be compatible with the stock SBT launcher script.

**Comment by fommil** [comment] 2015-08-17 13:57
yeah, we've seen a few people with this. It seems to be something to do with the `sbt` that you're using and possibly even Java version. We were unable to reliably reproduce on rory's machine. Try `git clean -fxd` and making sure you're definitely using paulp's script.

I'm guessing you're OS X?

**Comment by markschaake** [comment] 2015-08-17 14:06
> Try git clean -fxd and making sure you're definitely using paulp's script.

I gave paulp's script a shot last week and gave up after it wouldn't even launch the SBT console for me. I just gave it a second chance (with fresh install and also doing the `git clean -fxd` like you suggest):

```shell
➜  ensime-server git:(master) sbtp
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[info] Loading global plugins from /Users/markschaake/.sbt/0.13/plugins
[info] Loading project definition from /Users/markschaake/git/ensime-server/project
[info] Updating {file:/Users/markschaake/git/ensime-server/project/}ensime-server-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/markschaake/git/ensime-server/project/target/scala-2.10/sbt-0.13/classes...
[info] Set current project to ensime (in build file:/Users/markschaake/git/ensime-server/)
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
[warn] The `-` command is deprecated in favor of `onFailure` and will be removed in 0.14.0
➜  ensime-server git:(master)
```

Notice it just dumps me back to my zsh prompt after spitting out the warnings.

**Comment by fommil** [comment] 2015-08-17 14:12
what is `sbtp` actually doing? Because it looks like you're passing command line arguments to `sbt`.

**Comment by fommil** [comment] 2015-08-17 14:13
or, do you have an `SBT_OPTS` envar that is being inherited?

**Comment by markschaake** [comment] 2015-08-17 14:18
> or, do you have an SBT_OPTS envar that is being inherited?

That must have been it. I removed by `SBT_OPTS` env var and now the launcher seems to work fine.

Is there a plan to stay on paulp's launcher? At work, we are committed to staying on the standard SBT launcher (and pretty much standard everything else). For this reason, I will not be using paulp's launcher as my default (which is why I've installed it as `sbtp` and not `sbt`). I think for an OSS project, the more standard we can keep things the more approachable to potential contributors.

**Comment by fommil** [comment] 2015-08-17 14:37
we're sticking with paulp's launcher because the standard launcher:

1. doesn't allow `.jvmopts`
2. doesn't allow `.sbtopts`
3. doesn't set the Java version correctly

which makes it almost impossible to create reproducible builds.

I would argue that paulp's script is the standard way to invoke the launcher.

Did that fix the jerk tests for you?

**Comment by markschaake** [comment] 2015-08-17 15:02
> I would argue that paulp's script is the standard way to invoke the launcher.

I don't see it that way. It appears that paulp's script is influencing the future of the "standard" launcher in good ways. But the "standard" in my view (and the view of employers I've had past and present) is whatever is provided by the makers / maintainers of the tool (or what `brew install sbt` or `apt-get install sbt` installs). I believe that a primary goal of the Ensime core maintainers (you and rory at least) is to encourage a thriving OSS community and have the list of regular contributors grow. I am super excited about this and think you've done a tremendous job reviving Ensime. However, I think a stance like this undermines your goal because it currently requires contributors to use paulp's script which for many (like me) will incur a context-switching cost and can often times be that final barrier to entry to prevent me from helping out.

FWIW, after looking at paulp's script, I have no doubt that it offers superior functionality over the standard SBT launcher script. However, as my issue here illustrates, it is _not_ 100% compatible with it.

If you are dead-set on building the project with an alternative SBT launcher script, you should inform contributors of this fact. Please put it in the README with some FAQs or common gotchas. However, I encourage you not to do this and to try and keep the build compatible with the standard SBT launcher script.

> Did that fix the jerk tests for you?

Yes, jerk tests passed using paulp's script with my SBT_OPTS unset.

**Comment by markschaake** [comment] 2015-08-17 15:03
I just renamed the issue to better reflect the issue

**Comment by fommil** [comment] 2015-08-17 15:16
just you wait and see what the impact on your "context switch" will be when we show you how to fix this with stock `sbt` :wink: Then maybe you'll see why almost everybody uses paulp's script.

**Comment by fommil** [comment] 2015-08-17 15:27
This works

```
JAVA_OPTS="`cat .jvmopts | tr '\n' ' '`" /usr/bin/sbt jerk/test
```

I raised https://github.com/sbt/sbt/issues/2161 closing this as upstream bug.

@koshelev had the same problem, so flagging as an FAQ.

**Comment by fommil** [comment] 2015-08-17 15:31
Actually, that's not even enough... you actually need to do this https://github.com/sbt/sbt/issues/2162

```
JDK_HOME=`tail -1 .sbtopts` JAVA_HOME=`tail -1 .sbtopts` JAVA_OPTS="`cat .jvmopts | tr '\n' ' '`" /usr/bin/sbt
```

**Comment by fommil** [comment] 2015-08-17 15:40
(or set those settings globally, but since they are typically project specific, you can see why most people prefer paulp's script).

**Comment by fommil** [comment] 2015-08-17 16:20
FAQs are the first linked item from the CONTRIBUTING file, so it meets your criteria of documenting this for new contributors (as that is their first port of call).

**Closed by fommil** 2015-08-17 16:20 UTC
Labels: Externally Blocked, FAQ

**Comment by nafg** [comment] 2015-09-01 03:24
The default launcher does support .sbtopts

**Comment by paulp** [comment] 2015-09-01 07:03
The history has become understandably muddled in the minds of most, so allow me to clarify a few matters. When I called it "an alternative script for running sbt", it was an alternative to a one-line /bin/sh wrapper which invoked java, not to sbt-launcher-package's, which didn't and couldn't exist yet.

What is now being called the "standard" launcher was created by copying mine and tweaking it. [Here's where it first entered the sbt-launcher-package repository](https://github.com/sbt/sbt-launcher-package/blob/ff05caba8bd0951dd55dd6bd37f534982a0e01a3/src/universal/bin/sbt), before they finished deleting anything which might identify the original and still primary author.

So you're right: my runner, the original, isn't 100% compatible with the stripped down and modified fork, but it's not entirely possible to offer 100% compatibility with software which someone else introduces after the fact.

**Comment by nafg** [comment] 2015-10-27 07:38
@paulp ...other than that github says on top, "forked from paulp/sbt-extras"

**Comment by fommil** [comment] 2016-02-17 19:50
this is now documented in the Contributing guide, so removing FAQ flag
