### ISSUE TITLE
Make ensime 'port' file exists smarter

### ISSUE THREAD

**Issue by rorygraves** [ensime/ensime-server#505] opened 2014-07-11 16:16 UTC
i.e. check if the port is actually live otherwise replace the port file and run.

**Comment by albertmichaelj** [comment] 2015-01-12 16:33
I have this same problem on Windows but not on OS X. I think it has to do with Windows not correctly disconnecting from the server. I get the error "Server connection closed unexpectedly: connection broken by remote peer" anytime I kill the *inferior-ensime...* buffer in windows, and then when I re-open emacs and run M-x ensime it thinks a server process is already running, so it tells me to delete the port file. Is there an obvious fix for this? The temp directory thing wouldn't work if I was just opening and closing emacs throughout the day without a reboot.

**Comment by fommil** [comment] 2015-01-12 16:58
interesting. That must mean that the shutdown hooks to delete the port file are not running in windows. Perhaps emacs is more aggressively killing the server process.

**Comment by albertmichaelj** [comment] 2015-01-12 17:03
It's possible that it's unique to my particular emacs configuration on Windows, though I don't see why. Is there any information that I can provide to help isolate the issue?

**Comment by aemoncannon** [comment] 2015-01-12 17:09
One idea: Could be related to deleteOnExit not working for open files on
Windows. One thing to check would be if any process has the port file open
after the server is up and running. The prime suspect would be Emacs
itself. I seem to remember Process Explorer being useful for questions like
this.

**Comment by fommil** [comment] 2015-01-12 17:20
oh, maybe we actually need to set a `runShutdownHook` instead of `deleteOnExit`. I've found it to be more reliable. In fact, I'm certain I have a little utility function for this somewhere

(not quite what we want) https://github.com/fommil/common-utils/blob/master/src/main/java/com/github/fommil/utils/Workarounds.java

**Comment by edani** [comment] 2015-01-12 17:44
I've seen the same problem on Windows but I kept it on the back burner. There are two issues:
- killing the emacs buffer doesn't kill the process, so I have to kill it manually. It used to work though, so I'm thinking that once we stop using stb to launch ensime-server the problem will go away
- as you said,  deleteOnExit doesn't seem to be called when the process is killed in the task manager  (I don't see how it would actually)

**Comment by fommil** [comment] 2015-01-12 18:00
that sounds like a bug in emacs. Killing the buffer of a comint is supposed to kill any process associated to it.

**Comment by aemoncannon** [comment] 2015-01-12 18:03
Maybe dumb question: Why don't we delete the portfile immediately? ( why
wait)

**Comment by aemoncannon** [comment] 2015-01-12 18:03
Er.. Nm that is dumb. If no client ever connects it'll leak

**Comment by fommil** [comment] 2015-01-12 18:13
we could delete it when someone connects, but that might defeat the point of detecting existing servers and will bring its own problems.

**Comment by albertmichaelj** [comment] 2015-01-12 18:36
(I'm brand new to ensime) I'm a little confused. Let's see if I understand: When I run M-x ensime, I start and connect to an instance of the ensime-server. On Windows, when I kill the buffer or Emacs it is not killing the ensime-server process which, if it did, would clean up the port file automatically. Since the port file is not being deleted, does this mean that I'm spawning a bunch of orphaned ensime servers somewhere every time I run M-x ensime? If so, what's the process name to kill it manually? I haven't been able to find any process that I can identify as an instance of ensime-server.

I tried to see if any process associated with Emacs has a handle for the port file using Process Explorer, but there doesn't seem to be. Let me know if I can provide anything else to help identify the bug.

On OS X, it's a beautiful piece of software.

**Comment by edani** [comment] 2015-01-12 19:03
@albertmichaelj   on Windows (and probably every other OS)  `M-x ensime-shutdown`  does the right thing so that's the workaround for now.

**Comment by albertmichaelj** [comment] 2015-01-12 20:07
Thanks @edani, that works great! I still get the message `Server connection closed unexpectedly: connection broken by remote peer` when I use `M-x ensime-shutdown`, but the port file is correctly deleted and I can reconnect just fine.

**Comment by aemoncannon** [comment] 2015-01-15 16:42
Note: I tried calling delete-process on the server process on OSX. It kills the process immediately, and does *not* clean up the port file. Judging from the output it looks like it gets a SIGKILL. So whatever is happening when I kill the buffer on OSX, it's being more polite than delete-process.

We might be able to add a kill-buffer-hook to the server process, and send SIGINT ourselves with interrupt-process. Then again, maybe that's exactly what isn't working on Windows...

**Comment by aemoncannon** [comment] 2015-01-15 16:52
@albertmichaelj could you try evaluating: (-each ensime-server-processes 'interrupt-process) to see if that cleans the portfile?

**Comment by albertmichaelj** [comment] 2015-01-15 18:18
I just evaluated the list expression ``(-each ensime-server-processes 'interrupt-process)`` (using ``M-:``, is that what you wanted?), and it gave me the following the first time:

```
Debugger entered--Lisp error: (error "Process *inferior-ensime-server-C:\\Users\\albert_196\\Documents\\Projects\\aorta\\.ensime_cache*<2> is not active")
  interrupt-process(#<process *inferior-ensime-server-C:\Users\albert_196\Documents\Projects\aorta\.ensime_cache*<2>>)
  -each((#<process *inferior-ensime-server-C:\Users\albert_196\Documents\Projects\aorta\.ensime_cache*> #<process *inferior-ensime-server-C:\Users\albert_196\Documents\Projects\aorta\.ensime_cache*<2>> #<process *inferior-ensime-server-C:\Users\albert_196\Documents\Projects\aorta\.ensime_cache*>) interrupt-process)
  eval((-each ensime-server-processes (quote interrupt-process)) nil)
  eval-expression((-each ensime-server-processes (quote interrupt-process)) nil)
  call-interactively(eval-expression nil nil)
  command-execute(eval-expression)
```

And the command in the mini-buffer was ``Server connection closed unexpectedly: connection broken by remote peer``. After this the port file was gone, but it wouldn't let me reconnect to the ensime server using ``M-x ensime``. However, I couldn't repeat this behavior. Every other time I tried the command ``(-each ensime-server-processes 'interrupt-process)`` I got the error about the server connection closing unexpectedly, and it cleaned the portfile. I could then reconnect.

I can't remember what it does on OS X and I don't have my mac sitting here in front of me, so I'm not sure if the ``Server connection closed unexpectedly: connection broken by remote peer`` is unexpected behavior or not. It gives me the same message if I use ``M-x ensime-shutdown``.

Let me know if I can try anything else.

**Comment by aemoncannon** [comment] 2015-01-15 18:39
Server connection closed unexpectedly is expected. That's what we print
when we detect the connection was closed unexpectedly (in this case on the
server side).

I think the first backtrace was a result of a stale connection sitting in
ensime-server-processes.

The rest of your report is encouraging. Sounds like sigint does the job on
windows, so might be as simple as adding interrupt-process to
kill-buffer-hook for the server buffer.

**Comment by aemoncannon** [comment] 2015-01-15 21:18
@albertmichaelj Would you try evaluating the following while the inferior-server buffer is active?
(add-hook 'kill-buffer-hook 'interrupt-process nil t)
Then kill your server buffer. Is the portfile removed?

**Comment by albertmichaelj** [comment] 2015-01-15 21:23
Just did it, and it works if I manually kill the buffer (without closing emacs). However, if I close emacs with the inferior-server buffer still up, the port file is not deleted.

**Comment by aemoncannon** [comment] 2015-01-15 21:34
@albertmichaelj That's good. Now how about if you add:
(add-hook 'kill-emacs-hook 'interrupt-process nil t)

**Comment by albertmichaelj** [comment] 2015-01-15 22:53
Okay tried it, but it didn't work. I don't know if maybe kill-emacs-hook isn't correctly being called when I close emacs. It still works fine if I add-hook 'kill-buffer-hook and then close the buffer, but nothing happens if I add the kill-emacs-hook with or without the kill-buffer-hook as well. Is there a reason that kill-emacs-hook wouldn't be called?

**Comment by aemoncannon** [comment] 2015-01-15 23:21
Bummer. A long shot, but you might also try:
(add-hook 'kill-emacs-hook 'ensime-kill-all-ensime-servers)
That is, make it a global hook.

**Comment by aemoncannon** [comment] 2015-01-15 23:22
Btw, thanks for all your help testing : )

**Comment by aemoncannon** [comment] 2015-01-16 16:50
@albertmichaelj
To double-check that emacs is indeed calling the kill-emacs-hook, we could
try something like:
(add-hook 'kill-emacs-hook (lambda () (with-temp-file "~/test.txt" (insert
"exiting...")))

If it is indeed being called, then there is just something wrong with our
hook functions. Maybe try:
(add-hook 'kill-emacs-hook (lambda () (-each ensime-server-processes
'interrupt-process)))

I don't know windows well, but it's possible that the SIGINT-alike is being
superseded by a SIGTERM-alike when Emacs exits.

Have you checked whether exiting emacs actually cleans up servers, or if it
leaves orphans?

**Comment by albertmichaelj** [comment] 2015-01-16 16:57
I just tried ``(add-hook 'kill-emacs-hook 'ensime-kill-all-ensime-servers)``, but once I do, emacs won't even shut down. It give me the following error message when I try to shutdown emacs:

``kill-emacs: Symbol's function definition is void: ensime-kill-all-ensime-servers``

So, kill-emacs-hook is doing the correct thing, but somehow it's not correctly interrupting the process.

I'm happy to help. I appreciate the work that's gone into this piece of software. It works great on OS X.

**Comment by aemoncannon** [comment] 2015-01-16 17:10
Weird. Is the function defined before you try to exit? Should be in ensime-test.el

**Comment by fommil** [comment] 2015-01-16 17:13
ensime-test.el is not part of the ELPA distribution

**Comment by aemoncannon** [comment] 2015-01-16 17:15
Ah hah : ) OK maybe try the lambda I mentioned that calls interrupt process
on each.

**Comment by albertmichaelj** [comment] 2015-01-16 17:22
Yep, I got the package from ELPA, so I don't have it. 

``(add-hook 'kill-emacs-hook (lambda () (-each ensime-server-processes 'interrupt-process))) `` works. I don't know if there things I'm not seeing, but emacs closes cleanly and the port file is gone.

**Comment by aemoncannon** [comment] 2015-01-16 17:43
Great maybe we've got a plan. Would you like to put together a pull request?

Yep, I got the package from ELPA, so I don't have it.

(add-hook 'kill-emacs-hook (lambda () (-each ensime-server-processes
'interrupt-process))) works. I don't know if there things I'm not seeing,
but emacs closes cleanly and the port file is gone.

—
Reply to this email directly or view it on GitHub
<https://github.com/ensime/ensime-server/issues/505#issuecomment-70288531>.

**Comment by albertmichaelj** [comment] 2015-01-17 22:46
Let me know if you need anything else from me in terms of testing.

**Comment by aemoncannon** [comment] 2015-01-19 14:06
I'm going to wait for the no-fork stuff to go through first, as it'll touch
the same bits.

**Comment by aemoncannon** [comment] 2015-01-28 05:29
@albertmichaelj Would you test the PR I just created vs Windows?

**Comment by albertmichaelj** [comment] 2015-01-28 14:42
Unfortunately, I won't be able to test it out until early next week (traveling...), but I'd be happy to then. Could you give me more detailed instructions on how to test the fix? I've been using melpa to install packages for the most part so far.

**Comment by aemoncannon** [comment] 2015-01-28 16:01
I think once I fix the error I'll just merge. Our tests were pretty
conclusive.

**Comment by aemoncannon** [comment] 2015-01-29 04:14
@albertmichaelj When you get a chance, upgrade from melpa and see if the problem persists. Thanks

**Comment by albertmichaelj** [comment] 2015-02-02 15:22
Just got a chance to test it, and it works great. Port file is deleted when Emacs is closed as well as if I kill the inferior-ensime buffer. It looks like it is fixed to me.

**Comment by aemoncannon** [comment] 2015-02-02 16:25
Hot damn! Thanks

**Closed** 2015-02-02 16:26 UTC
Labels: Blocked, Emacs

**Comment by fommil** [comment] 2015-02-02 17:29
w00t!
