### ISSUE TITLE
OrientDB integration

### ISSUE THREAD

**Issue by taburet** [ensime/ensime-server#1708] opened 2017-01-23 09:52 UTC
It's started from [that tweet](https://twitter.com/fommil/status/821974729439514624).

Could you guys please provide directions on how to run problematic tests/benchmarks locally w/o involving Docker and all the heavy tech, so I may attach the profiler and debugger easily. Maybe you have some internal benchmarks that are not published in the repo?

**Comment by fommil** [comment] 2017-01-23 10:02
@sugakandrey

**Comment by fommil** [comment] 2017-02-07 11:08
@taburet our graph branch is now passing the tests (including integration tests) on a fast machine, but orient is too slow for our CI.

To reproduce, check out this PR https://github.com/ensime/ensime-server/pull/1681

You only need two dependecies: java 8 and sbt. The latter is just a shell script (but will download a lot of jars into `~/.ivy2` and `~/.sbt` that you can safely clean up after). Instructions to install `sbt` here http://ensime.org/learning_scala/#install (I assume you have Java 8 and potentially `jenv`).

```
git clone https://github.com/sugakandrey/ensime-server.git
cd ensime-server
git checkout 2.0-graph
sbt core/it:testOnly *BasicWorkflow
```

the first time you run the `sbt` command it will be very very slow while it grabs dependencies and compiles the entire project. The second time you run it, it will launch the slow integration test as a subprocess of sbt almost immediately.

I have performed a YourKit CPU snapshot and methods like `com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ORecord, String, ODatabase$OPERATION_MODE, boolean, ORecordCallback, ORecordCallback) ODatabaseDocumentTx.java` are the biggest culprits.

**Comment by fommil** [comment] 2017-02-07 11:16
btw, I should point out that our CI is running on a ramdisk and that this branch is about 10x slower than the H2 solution we have (at writing).

**Comment by taburet** [comment] 2017-02-07 15:41
Thank you, lets see what we can do about it.

**Comment by taburet** [comment] 2017-02-08 07:27
`sbt ensimeConfig` line is giving following errors:

```
[warn]   https://repo1.maven.org/maven2/javax/activation/activation/1.1/activation-1.1-javadoc.jar
[warn]   https://repo1.maven.org/maven2/stax/stax-api/1.0.1/stax-api-1.0.1-javadoc.jar
[warn]   https://repo1.maven.org/maven2/stax/stax-api/1.0.1/stax-api-1.0.1-sources.jar
java.lang.RuntimeException: failed to resolve (Dependency(org.ensime:server_2.12,1.0.0,compile,Set(),Attributes(jar,),false,true),List(not found: https://repo1.maven.org/maven2/org/ensime/server_2.12/1.0.0/server_2.12-1.0.0.pom, not found: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/server_2.12/1.0.0/server_2.12-1.0.0.pom))
	at org.ensime.EnsimeCoursierPlugin$$anonfun$resolve$1.apply(EnsimeCoursierPlugin.scala:84)
	at org.ensime.EnsimeCoursierPlugin$$anonfun$resolve$1.apply(EnsimeCoursierPlugin.scala:83)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.ensime.EnsimeCoursierPlugin$.resolve(EnsimeCoursierPlugin.scala:83)
	at org.ensime.EnsimeCoursierPlugin$.resolveEnsimeJars(EnsimeCoursierPlugin.scala:104)
	at org.ensime.EnsimeCoursierPlugin$$anonfun$buildSettings$5.apply(EnsimeCoursierPlugin.scala:62)
	at org.ensime.EnsimeCoursierPlugin$$anonfun$buildSettings$5.apply(EnsimeCoursierPlugin.scala:62)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] ({.}/*:ensimeServerJars) failed to resolve (Dependency(org.ensime:server_2.12,1.0.0,compile,Set(),Attributes(jar,),false,true),List(not found: https://repo1.maven.org/maven2/org/ensime/server_2.12/1.0.0/server_2.12-1.0.0.pom, not found: https://oss.sonatype.org/content/repositories/snapshots/org/ensime/server_2.12/1.0.0/server_2.12-1.0.0.pom))
[error] Missing task key: ensimeServerJars
java.lang.IllegalArgumentException
	at org.ensime.CommandSupport$.org$ensime$CommandSupport$$fail(EnsimePlugin.scala:662)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:677)
	at org.ensime.CommandSupport$RichTaskKey$$anonfun$run$1.apply(EnsimePlugin.scala:677)
	at scala.Option.getOrElse(Option.scala:120)
	at org.ensime.CommandSupport$RichTaskKey.run(EnsimePlugin.scala:677)
	at org.ensime.EnsimePlugin$$anonfun$ensimeConfig$1.apply(EnsimePlugin.scala:269)
	at org.ensime.EnsimePlugin$$anonfun$ensimeConfig$1.apply(EnsimePlugin.scala:232)
	at sbt.Command$$anonfun$sbt$Command$$apply1$1$$anonfun$apply$6.apply(Command.scala:71)
	at sbt.Command$.process(Command.scala:93)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
	at sbt.State$$anon$1.process(State.scala:184)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.MainLoop$.next(MainLoop.scala:96)
	at sbt.MainLoop$.run(MainLoop.scala:89)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
	at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
	at sbt.Using.apply(Using.scala:24)
	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
	at sbt.MainLoop$.runLogged(MainLoop.scala:22)
	at sbt.StandardMain$.runManaged(Main.scala:57)
	at sbt.xMain.run(Main.scala:29)
	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
	at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
	at xsbt.boot.Launch$.run(Launch.scala:109)
	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
	at xsbt.boot.Launch$.launch(Launch.scala:117)
	at xsbt.boot.Launch$.apply(Launch.scala:18)
	at xsbt.boot.Boot$.runImpl(Boot.scala:41)
	at xsbt.boot.Boot$.main(Boot.scala:17)
	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.IllegalArgumentException
[error] Use 'last' for the full log.
```

Seems like something wrong with versioning here, since it clearly builds 2.0.0 and refers to 1.0.0 somewhere. Unless you use some kind of a bootstrapping :)

**Comment by fommil** [comment] 2017-02-08 07:37
Oh yes sorry, if you don't actually use ensime, you'll need to create a stub ensime.sbt file, as shown in the .drone.yml file.

**Comment by taburet** [comment] 2017-02-08 07:49
Thanks, that fixed the problem. Launching the test.

**Comment by fommil** [comment] 2017-02-12 23:05
@taburet we are now investigating a way of speeding up the CI so we can merged this... we're building up the orientdb for a "typical test" and then re-using it in all the tests. It's having a huge benefit on our CI times (but obviously not addressing the fundamental problem).

However, even though we close down the DB in each of our tests, we're seeing direct memory leaking and we're getting OOMs. Do we need to do anything beyond call `close` on the `OrientGraphFactory`?

BTW, almost all the code that's relevant for you to look at is in `GraphService.scala` which defines the entire interface with orientdb.

**Comment by fommil** [comment] 2017-02-12 23:11
And also the `SimpleOrient.scala` file, doh! Sorry this one is also important.

Something that I'm sure would really help speed up our insertions would be if there was a fast UPSERT. You'll see we do a get and either a create or an update.

**Comment by fommil** [comment] 2017-02-12 23:14
to reproduce the OOM, follow the (new) instructions in the `.drone.yml` to pre-warm a cache

```
cd testing/cache && sbt ++2.12.1 ensimeConfig ensimeServerIndex && cd ../..
```

and then run

```
sbt "core/it:testOnly *RichPresentationCompilerSpec"
```

**Comment by fommil** [comment] 2017-02-12 23:16
incidentally, deleting the `.ensime_cache` and running `sbt ++2.12.1 ensimeServerIndex` in the `testing/cache` directory is a great metric to improve. This is the slowest part of orient for us.

**Comment by fommil** [comment] 2017-02-12 23:28
FYI http://stackoverflow.com/questions/17671066/java-direct-memory-using-sun-misc-cleaner-in-custom-classes

which classes are you storing in direct memory?

**Comment by fommil** [comment] 2017-02-12 23:31
(another option would be to allow us to disable direct memory when running the integration tests)

**Comment by fommil** [comment] 2017-02-12 23:37
```
    OGlobalConfiguration.DIRECT_MEMORY_TRACK_MODE.setValue(true)
```

doesn't help

**Comment by fommil** [comment] 2017-02-12 23:44
I seem to have worked around the issue by re-using the same DB instance for all the tests in this spec... but that's a really nasty hack.

**Comment by fommil** [comment] 2017-02-12 23:51
I spoke too soon. It lets me run that one test suite, but when running all the tests, it blows up again.

There is definitely a direct memory leak.

**Comment by fommil** [comment] 2017-02-12 23:52
@sugakandrey ^^^ incase you missed

**Comment by taburet** [comment] 2017-02-13 07:15
What I have found so far:

1. Turning transactions/WAL on and wrapping foreach body into a transaction in GraphService.persist shaves about 30% from execution time. Graph/Blueprints API is an immediate mode API, every tiny change is immediately written to disk, using transactions we may accumulate changes for some period and write them in a single chunk.

2. 30-50% of remaining execution time is spent waiting for GC. Apparently, something is changed in the graph branch besides the storage layer. In master branch heap usage is stable at around 300MB, while in graph branch it quickly climbs up to Xmx and stays high, the heap is mostly flooded with strings and char[]. Will investigate more on this.

3. Another strange sign, if GraphService.persist is completely commented out, the execution time on graph branch is still 2-3 times the execution time of master branch. Is there a chance that on graph branch some new features/bugs were added which require more work to be done?

4. Seems like there are problems with schema or data insertion, some properties are marked as mandatory, but there are no values for them provided on insertion/upsert.

Regarding direct memory and OOMs, lets first make sure that is not a configuration problem. Please find "OrientDB auto-config DISKCACHE=..." line in the log, it contains information about auto-configured memory settings. I suspect the settings are just too high.

**Comment by fommil** [comment] 2017-02-13 07:54
Oh wow, glad to hear you've been looking into this in such detail! I did some transaction speed tests 9 months ago and concluded it was slower, maybe things changed.

**Comment by fommil** [comment] 2017-02-13 08:18
Yes there are some extra features in the graph branch, but we seen big slowdowns in an earlier feature-parity commit. I'll have a look at that to make sure we haven't done something silly in the data generation: it would definitely show up under a cpu profile.

As I see it, there are a few problems, in priority:

1. Memory leak when we try to re-use existing databases (highest priority because it blocks our ability to merge). Let's hope it's config!
2. Even when reusing DBs, the tests are slower. I wouldn't expect any degradation in read perf because we don't read much in our queries.
3. Write perf is *way* slower. This is what I thought our problem was.
4. We might have also introduced perf regressions. We'll look into that.

**Comment by taburet** [comment] 2017-02-13 08:29
BTW, additional time maybe saved in SimpleOrient.insertV, multiple calls to `v.setProperty` maybe changed to a single `v.setProperties`, but that requires `v` to be an instance of `OrientElement`.

Please also inspect the contents of `java.nio:type=BufferPool,name=direct`, `java.lang:type=Memory` and `com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean` JMX beans to diagnose memory problems better.

**Comment by taburet** [comment] 2017-02-14 12:19
To summarise all my findings:

* BasicWorkflow on master branch gave a baseline of 15-20 seconds per run.

* Initial testing of BasicWorkflow on graph branch gave 110-115 seconds per run. That is 5-7 times slower than master branch.

* Added transactions and `setProperties` to graph branch which gave 65-70 seconds per run. That is 3-5 times slower than master.

* Noticed big GC pauses on graph branch and -Xmx of 1GB, benchmarked master with 1GB heap. 20-25 seconds per run, 2-3 times faster than graph.

* Profiled memory allocations on both branches. There are no big and long-lived allocations on master while on graph there is a massive amount of long-lived instances of `scala.collection.immutable.$colon$colon` holding about 650MB of the heap, together with other smaller instances of Scala-related classes they consume about 700MB in the old gen pool. JVM frequently runs out of space in the young gen with 1GB heap and tries to do a collection of the old gen which isn't cheap. On master branch the old gen is always bellow 150MB.

* Benchmarked both branches on 4GB heap to eliminate the GC overhead, master – 15-20 seconds per run, graph – 45-50 seconds, that's 2-3 times slower.

* Benchmarked graph with persistence turned off (Lucene-based IndexService is on) – 25-30 seconds, so there is a surplus of about 10 seconds even w/o persistence comparing to master. If we subtract the surplus from graph results on 4GB heap this gives 35-40 "adjusted" seconds per run as a very rough and questionable estimate :) That's is about only 2 times slower.

I think that is a good result, especially if we take into account that there is obviously more work being done in graph branch and probably more data being saved.

**Comment by rorygraves** [comment] 2017-02-14 13:12
Wow. Thank you @taburet. That is a great analysis and hugely helpful.

**Comment by fommil** [comment] 2017-02-14 13:34
yeah, this is really good work! :smile: And I thought you'd just look at the code and say "try increasing the heap size" :rofl:

**Comment by lvca** [comment] 2017-02-15 07:02
@fommil So how are performance now?

**Comment by fommil** [comment] 2017-02-15 07:33
@Ivca we need to find the time to implement these changes. I'm hoping Andrey has some numbers for us by the weekend.

**Comment by sugakandrey** [comment] 2017-02-25 00:10
@taburet I tried implementing the changes you suggested and while using alternative vertex constructor (instead of setting properties one by one) doest speed things up, I did't have much success with adding transactions. Simply wrapping `foreach` in `persist()` into a transaction slows things down about 30% for me. Should I be using some alternative API to avoid immediate writes here? Perhaps you could share the changes you made, when testing, would be much appreciated :). Thanks for the awesome analysis btw.

**Comment by sugakandrey** [comment] 2017-02-25 10:28
@taburet Thanks, I used SSD.

**Comment by fommil** [comment] 2017-02-25 16:51
we use RAM drive in CI

**Comment by fommil** [comment] 2017-04-15 17:01
I'm getting an OOM when I run `core/it:testOnly *Semantic*`

**Comment by fommil** [comment] 2017-04-15 17:04
yeah, there is almost certainly a memory leak and OrientDB is not closing its direct memory when a graph is closed.

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:311)
	at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:264)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1280)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:656)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.restoreQueueWithPageLoad(O2QCache.java:805)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.restoreQueue(O2QCache.java:710)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.loadCacheState(O2QCache.java:675)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:324)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPooled.internalOpen(OPartitionedDatabasePool.java:447)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:310)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:268)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:143)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory$2.getGraph(OrientGraphFactory.java:116)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:240)
	at org.ensime.indexer.graph.GraphService.db$lzycompute(GraphService.scala:152)
	at org.ensime.indexer.graph.GraphService.db(GraphService.scala:129)
	at org.ensime.indexer.graph.GraphService.$anonfun$shutdown$2(GraphService.scala:172)
```

**Comment by fommil** [comment] 2017-04-15 17:15
exception occurs even if I apply the commit to be transactional

**Comment by fommil** [comment] 2017-04-15 17:26
how interesting... enabling the log seems to make the problem go away! Needs further investigation.

**Comment by fommil** [comment] 2017-04-15 18:12
getting a little further, only getting OOM in `core/it:testOnly *Debug*`. I'm wondering if we properly close everything in the project fixtures.

**Comment by fommil** [comment] 2017-04-15 19:10
we definitely close everything. I'm still convinced there is a direct memory leak somewhere.

**Comment by fommil** [comment] 2017-04-15 19:28
I got green lights locally.... but *reducing* the mx to 1gb. I have a working theory that there are two memory leaks:

1. if a graph is created and shutdown immediately (no ops)
2. if the heap ms doesn't match the mx. Perhaps a bug in free memory calculation?

**Comment by fommil** [comment] 2017-04-15 19:33
hmm, seems if I set heap to 2gb I get this

```
17:32:11.940 INFO   com.orientechnologies - OrientDB auto-config DISKCACHE=1,820MB (heap=1,820MB direct=1,820MB os=62,521MB), assuming maximum direct memory size equals to maximum JVM heap size
17:32:11.940 WARN   java.lang.Class - MaxDirectMemorySize JVM option is not set or has invalid value, that may cause out of memory errors. Please set the -XX:MaxDirectMemorySize=62521m option when you start the JVM.
```

in the logs and almost certainly an OOM when running the tests.

So my theory is that there is a bug somewhere in the orientdb direct memory sweeper. I'd like some way to be able to just clear the memory on demand.

**Comment by fommil** [comment] 2017-04-15 19:35
@taburet any ideas why we get OOM when we use larger heap?

**Comment by fommil** [comment] 2017-04-15 19:41
I must admit, I'm not very happy that OrientDB uses direct memory. It would be far better if this was a flag. It completely messes all our CI memory tuning and it's never good to break outside of the JVM model.

**Comment by fommil** [comment] 2017-04-15 19:47
hmm, `DebugTest` gives some weird things

```
20:46:15.853 WARN  akka://default/user/project org.ensime.core.Project - Refresh failed: com.orientechnologies.orient.core.exception.OValidationException: The field 'Field.access' is mandatory, but not found on record: Field{fqn:stepping.ForComprehensionListString2$.MODULE$,typehint:Field}
```

**Comment by fommil** [comment] 2017-04-15 19:51
yup, `Field`s are getting created with `null` Access.

**Comment by fommil** [comment] 2017-04-15 19:52
quite explicitly, in fact...

```scala
    case cn: ClassName if !cn.isPrimitive => Some(ClassDef(name.fqnString, null, null, None, None, null, None, None))
    case fn: FieldName => Some(Field(name.fqnString, None, None, None, null, None))
    case mn: MethodName => Some(Method(name.fqnString, None, None, null, None))
```

**Comment by sugakandrey** [comment] 2017-04-15 19:56
Some fields are set as `null`, because we don't know thier values yet, but need to insert something in order to create an edge (e.g. we are inserting a super-class vertex). They should be initialized later.

**Comment by fommil** [comment] 2017-04-15 19:56
this is all over this file.... @sugakandrey why are we inserting `null` ?

**Comment by fommil** [comment] 2017-04-15 19:57
@sugakandrey that sounds like we got the modelling wrong. We should never need to do that. If we don't know some information at the point of insertion, it should be a different vertex that is added later.

**Comment by fommil** [comment] 2017-04-15 19:58
also, there is no reason why all FQNs need to have something like a filename on them... that's a perfect case for all the FQNs in a given class/source file to point to one vertex holding this information.

**Comment by fommil** [comment] 2017-04-15 20:02
I see, so this is when it's the target vertex. e.g. to set "my interfaces".

**Comment by fommil** [comment] 2017-04-15 20:03
we can't have `setMandatory(true)` and `setNotNull(true)` in that case.

**Comment by fommil** [comment] 2017-04-15 20:14
I think we need the ability to point at vertices that haven't been created yet, don't we?

**Comment by fommil** [comment] 2017-04-15 20:23
it's that, or we end up doing a two pass index. Once for vertices, again for edges. That sounds nuts.

**Comment by fommil** [comment] 2017-04-15 20:24
these OOMs are driving me absolutely crazy. I'm about 5 seconds away from just writing a god damned graph database myself.

**Comment by lvca** [comment] 2017-04-15 20:37
Hi @fommil please try leaving the default setting `-XX:MaxDirectMemorySize=512g`. This is just an upper limit for the JVM (and can't be set at run-time). If you want to tune the DISKCACHE, than use the setting `-Dstorage.diskCache.bufferSize=1000` to allocate 1GB of diskcache to OrientDB. The rule of the thumb is that maxheap + diskcache should never be bigger than the available RAM. I hope this helps.

**Comment by taburet** [comment] 2017-04-15 20:42
@fommil Inspect the contents of `java.nio:type=BufferPool,name=direct` JMX bean, if the value doesn't go above the configured `storage.diskCache.bufferSize` everything is fine and there are no leaks.

**Comment by fommil** [comment] 2017-04-15 20:45
@Ivca you mean `m`, not `g`?

what's the relation between direct memory and the diskcache? I don't want *any* direct memory here, I want to fully control the RAM requirements of the app.

**Comment by lvca** [comment] 2017-04-15 20:46
@fommil I mean `g`. It just an upper limit, if you have a 64bit system, try to leave it that big.

**Comment by fommil** [comment] 2017-04-15 20:47
@Ivca doesn't that give the app the ability to eat all the RAM on the machine? Absolutely no way.

**Comment by fommil** [comment] 2017-04-15 20:49
setting `512m` helps. I don't understand why setting a low direct memory value helps here.

**Comment by fommil** [comment] 2017-04-15 21:00
@taburet `java.nio:type=BufferPool,name=direct` is count=38, MemoryUsed=539327595. Not sure how to get `storage.diskCache.bufferSize`

**Comment by lvca** [comment] 2017-04-15 21:09
OrientDB uses the setting `storage.diskCache.bufferSize` if any, the `-XX:MaxDirectMemorySize` should be bigger than `storage.diskCache.bufferSize` otherwise you get `java.lang.OutOfMemoryError: Direct buffer memory`. If you don't trust OrientDB with a huge number, at least set it to a value bigger than diskcache.

**Comment by fommil** [comment] 2017-04-15 21:12
@Ivca what's the default? When I set direct access to a lower value, it seems more stable so I don't think this is about setting it *larger* than anything.

Shouldn't you be namespacing your sys properties with, e.g. `orientdb.storage.diskCache.bufferSize`?

**Comment by fommil** [comment] 2017-04-15 21:13
seems I can configure it with `OGlobalConfiguration.DISK_CACHE_SIZE.setValue(256)` and the default is 4gb?

**Comment by fommil** [comment] 2017-04-15 21:21
thanks @taburet / @Ivca ! Setting the disk cache size to a much smaller number that 4gb really helps and now I can set a low direct memory number and run all tests without OOM.

I think we'd like to launch the next version of ensime with orientdb, but I suspect we might move to something more lightweight... possibly just a key/value store for vertices and a fast write tuple store for vertices. That way we can also use our own typesafe marshalling instead of having to rely on java serialisation... reading is not a problem for us but optimised writing is a huge deal and we don't really care about transactions or a query language because we can write a DSL to exactly match our data model.

**Closed** 2017-04-15 21:27 UTC
Labels: Indexer

**Comment by lvca** [comment] 2017-04-15 21:37
@fommil When you're ready to expore alternative I'm curious about the performance of other key/value datastores in comparison to OrientDB, but used as Key/Value. By the way OrientDB v3.0 is much lighter and faster than 2.2. Furthermore we get rid of all the dependencies from TinkerPop (now it's a separate module), so the entire OrientDB server is a few MB now.

**Comment by fommil** [comment] 2017-04-15 21:44
@Ivca that's very interesting! What's the status of v3.0?

**Comment by lvca** [comment] 2017-04-15 21:47
We already pack 3.0M1, it will be released on Tuesday but it's not production ready. We think to release 3.0M1, then 3.0RC1 and when we reach the stability we can do 3.0GA. I think 3.0GA could be out in 2 months from now.

**Comment by fommil** [comment] 2017-04-15 21:49
ok cool, we'll keep it in mind. Is it pure Java?

**Comment by lvca** [comment] 2017-04-15 21:56
Yes, no JNI.

**Comment by fommil** [comment] 2017-04-15 22:11
(I was mostly concerned about internally using a specific version of Scala, like neo4j does, but yes not using JNI is always good! Been very guilty of that myself)

**Comment by fommil** [comment] 2017-04-15 22:12
It sounds like v3.0 is basically exactly what we wanted all along! Is it a rewrite?

**Comment by lvca** [comment] 2017-04-15 22:49
Yes for the SQL Engine and the Graph API.
