### ISSUE TITLE
Create diffs for NewFile and DeleteFile edits in FileUtil.

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1368] opened 2016-03-30 17:41 UTC
`FileUtil` in `writeDiffChanges` method should be able to handle not only `TextEdit`s, but also changes that are of types `NewFile` and `DeleteFile`. Depending on the type of `FileEdit`, different `FileEditHelper.diffFrom*` method should be called. The missing ones are `FileEditHelper.diffFromNewFile` and `FileEditHelper.diffFromDeleteFile`. They are necessary to create diff files with proper contents.

**Comment by fommil** [comment] 2016-03-30 18:45
This would be a good one! I think it might be a dupe as I remember @greenrd wanting to look at it.

**Comment by fommil** [comment] 2016-03-31 21:38
dupe of #1283

**Closed by fommil** 2016-03-31 21:38 UTC
Labels: Low Hanging Fruit
