### ISSUE TITLE
implement Language Server Protocol

### ISSUE THREAD

**Issue by mickaelistria** [ensime/ensime-server#1584] opened 2016-08-11 06:46 UTC
lt would be great if Ensime implemrnted the Language Server Protocol, for which multiple tools already have integrations or plans of integration.
https://github.com/Microsoft/language-server-protocol

**Comment by ktonga** [comment] 2016-08-11 06:54
Duplicate of #1498

**Closed by ktonga** 2016-08-11 06:54 UTC
