### ISSUE TITLE
ensime-inf-switch fails because classpath property is a list of strings.

### ISSUE THREAD

**Issue by coventry** [ensime/ensime-server#847] opened 2015-02-27 20:21 UTC
When I run `C-c C-v z` (`M-x ensime-inf-switch`), it fails with the following backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument stringp ("my" "class" "path"))
  start-process("ensime-inferior-scala" #<buffer *ensime-inferior-scala*> "scala" "-classpath" ("my" "class" "path"))
  apply(start-process "ensime-inferior-scala" #<buffer *ensime-inferior-scala*> "scala" ("-classpath" ("my" "class" "path")))
  start-file-process("ensime-inferior-scala" #<buffer *ensime-inferior-scala*> "scala" "-classpath" ("my" "class" "path"))
  apply(start-file-process "ensime-inferior-scala" #<buffer *ensime-inferior-scala*> "scala" ("-classpath" ("my" "class" "path")))
  comint-exec-1("ensime-inferior-scala" #<buffer *ensime-inferior-scala*> "scala" ("-classpath" ("my" "class" "path")))
  comint-exec(#<buffer *ensime-inferior-scala*> "ensime-inferior-scala" "scala" nil ("-classpath" ("my" "class" "path")))
  (let ((conn (or (ensime-connection-or-nil) (ensime-prompt-for-connection))) (root-path (or (ensime-configured-project-root) ".")) (cmd-and-args (ensime-inf-get-repl-cmd-line))) (switch-to-buffer-other-window (get-buffer-create ensime-inf-buffer-name)) (ensime-inf-mode) (cd root-path) (ensime-assert-executable-on-path (car cmd-and-args)) (comint-exec (current-buffer) "ensime-inferior-scala" (car cmd-and-args) nil (cdr cmd-and-args)) (setq ensime-buffer-connection conn) (let ((proc (get-buffer-process (current-buffer)))) (ensime-set-query-on-exit-flag proc)))
  ensime-inf-run-scala()
  (if (and (get-buffer ensime-inf-buffer-name) (ensime-inf-process-live-p ensime-inf-buffer-name)) (switch-to-buffer-other-window ensime-inf-buffer-name) (ensime-inf-run-scala))
  (if (equal ensime-inf-buffer-name (buffer-name)) (switch-to-buffer-other-window (other-buffer)) (if (and (get-buffer ensime-inf-buffer-name) (ensime-inf-process-live-p ensime-inf-buffer-name)) (switch-to-buffer-other-window ensime-inf-buffer-name) (ensime-inf-run-scala)))
  ensime-inf-switch()
  call-interactively(ensime-inf-switch nil nil)
```

As a quick fix, I built the repl command "manually" with the classpath as a concatenated list separated by colons, and it worked.  However, I don't know what else this breaks.  Anyway, with this function `C-c C-v z` does what I expect.

```elisp
(defun ensime-inf-get-repl-cmd-line ()
  "Get the command needed to launch a repl, including all
the current project's dependencies. Returns list of form (cmd [arg]*)"
  (if (and (ensime-connected-p) (ensime-analyzer-ready))
      `("scala" "-classpath" ,(mapconcat 'identity (plist-get (ensime-rpc-repl-config) :classpath) ":"))
    ensime-inf-default-cmd-line))
```

Maybe I have some incompatible library preventing ensime from turning `(plist-get (ensime-rpc-repl-config) :classpath)` from a list into a concatenated string?  How is this supposed to work?

**Comment by aemoncannon** [comment] 2015-02-27 20:31
Hiya. Looks like a regression. Want to do a PR?

It may be of interest that we plan to get rid of ensime-rpc-repl-config and
simply derive the classpath from the ensime config, which is available
locally.

Something like:
(defun ensime-inf-get-repl-cmd-line ()
  (when (ensime-connected-p)
        `("scala" "-classpath" (ensime-config-build-repl-classpath
(ensime-config)))))

Where 'ensime-config-build-repl-classpath' would need to be defined in
ensime-config.el

**Comment by fommil** [comment] 2015-02-27 20:41
yup dupe of #642, we'd love a PR on this! It shouldn't be too hard either

**Closed by fommil** 2015-02-27 20:41 UTC

**Comment by coventry** [comment] 2015-02-27 22:44
Hmm.  I can probably do a PR, but I'm new to scala and don't fully understand #642.  What is the alternative to calling the scala binary, exactly?

It looks like a jumped on the melpa version of ensime at a time when the codebase is a bit unstable.  Can you please recommend a stable version I could use for production work?

**Comment by fommil** [comment] 2015-02-27 22:48
@coventry this is the most stable version there is. We're working towards 1.0 and this is actually on the roadmap.

If you want a quick workaround, just use the sbt command `console` to get a REPL.

With regards to a PR, all you need to do is to aggregate all the jar files from the ensime config file and call out to the `$JAVA_HOME/bin/java` system binary with the jars on the classpath and calling the class `scala.tools.nsc.MainGenericRunner`

**Comment by fommil** [comment] 2015-02-27 22:49
(btw, this is a pure elisp task, so no need to be a Scala expert :smile:)

**Comment by fommil** [comment] 2015-02-27 22:50
we should also probably reconcile our REPL mode with the one in `sbt-mode` as there is a lot of common functionality there.

**Comment by coventry** [comment] 2015-02-28 00:18
OK, so pull the jars from `:compile-deps` in `.ensime` and make a classpath out of that?  Sounds simple enough.  Can there be more than one subproject in `.ensime`?  If so, how to distinguish the correct one?

**Comment by fommil** [comment] 2015-02-28 00:22
@coventry yup! just aggregate all of them

**Comment by fommil** [comment] 2015-02-28 00:23
@coventry if you want an example .ensime run `gen-ensime` on my branch of ensime: https://github.com/fommil/ensime-server/tree/modularise (will be master very soon)

**Comment by aemoncannon** [comment] 2015-02-28 01:08
@coventry Also, there's some elisp in ensime-config.el that demonstrates
collecting things from all submodules into a single list. Best.

**Comment by coventry** [comment] 2015-02-28 03:15
> yup! just aggregate all of them

Won't that cause mysterious problems down the line for some poor soul who inherits a project where subprojects depend on different but identically named jars?

**Comment by aemoncannon** [comment] 2015-02-28 03:32
Even if their names are the same, their paths will be different, so
shouldn't be a problem.

**Comment by fommil** [comment] 2015-02-28 09:26
when you have the list, just remove duplicates (the same jar may appear in several modules, and it usually points to the same location in the ivy/maven cache).

**Comment by coventry** [comment] 2015-03-01 01:59
My changes are at https://github.com/coventry/ensime-emacs/commits/new-repl-launch-logic but it's not ready for a PR.  The java invocation fails with `Could not find or load main class scala.tools.nsc.MainGenericRunner`.  I'm also still not convinced this way of constructing the classpath is appropriate.

**Comment by MartinSoto** [comment] 2015-05-31 18:48
Just installed 20150531.712 on Ubuntu and this issue still seems to be around. Any chances of getting a working REPL any time soon?

**Comment by fommil** [comment] 2015-05-31 18:50
@MartinSoto start the ensime server before calling this function.

**Comment by MartinSoto** [comment] 2015-05-31 19:05
@fommil, I'm starting the server before trying to go to the REPL. My steps:
* Start emacs.
* Load a scala source file from my already initialized project.
* Run `M-x ensime`. This one seems to work well. After running it, the following command is on my process list:
```
usr/lib/jvm/java-7-openjdk-amd64/bin/java -classpath /usr/lib/jvm/java-7-openjdk-amd64/lib/tools.jar:/home/msoto/.sbt/boot/scala-2.10.4/lib/scala-compiler.jar:/home/msoto/.sbt/boot/scala-2.10.4/lib/scala-library.jar:/home/msoto/.sbt/boot/scala-2.10.4/lib/scala-reflect.jar:/home/msoto/.ivy2/cache/org.ensime/ensime_2.10/jars/ensime_2.10-0.9.10-SNAPSHOT.jar:/home/msoto/.ivy2/cache/com.chuusai/shapeless_2.10.4/bundles/shapeless_2.10.4-2.0.0.jar:/home/msoto/.ivy2/cache/com.github.stacycurl/pimpathon-core_2.10/jars/pimpathon-core_2.10-1.2.0.jar:/home/msoto/.ivy2/cache/org.parboiled/parboiled-scala_2.10/bundles/parboiled-scala_2.10-1.1.6.jar:/home/msoto/.ivy2/cache/org.parboiled/parboiled-core/bundles/parboiled-core-1.1.6.jar:/home/msoto/.ivy2/cache/com.h2database/h2/jars/h2-1.4.182.jar:/home/msoto/.ivy2/cache/com.typesafe.slick/slick_2.10/bundles/slick_2.10-2.1.0.jar:/home/msoto/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/msoto/.ivy2/cache/com.jolbox/bonecp/bundles/bonecp-0.8.0.RELEASE.jar:/home/msoto/.ivy2/cache/com.google.guava/guava/bundles/guava-15.0.jar:/home/msoto/.ivy2/cache/org.apache.commons/commons-vfs2/jars/commons-vfs2-2.0.jar:/home/msoto/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.1.jar:/home/msoto/.ivy2/cache/org.apache.maven.scm/maven-scm-api/jars/maven-scm-api-1.4.jar:/home/msoto/.ivy2/cache/org.codehaus.plexus/plexus-utils/jars/plexus-utils-1.5.6.jar:/home/msoto/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svnexe/jars/maven-scm-provider-svnexe-1.4.jar:/home/msoto/.ivy2/cache/org.apache.maven.scm/maven-scm-provider-svn-commons/jars/maven-scm-provider-svn-commons-1.4.jar:/home/msoto/.ivy2/cache/regexp/regexp/jars/regexp-1.3.jar:/home/msoto/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-4.7.2.jar:/home/msoto/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-4.7.2.jar:/home/msoto/.ivy2/cache/org.ow2.asm/asm-commons/jars/asm-commons-5.0.3.jar:/home/msoto/.ivy2/cache/org.ow2.asm/asm-tree/jars/asm-tree-5.0.3.jar:/home/msoto/.ivy2/cache/org.ow2.asm/asm/jars/asm-5.0.3.jar:/home/msoto/.ivy2/cache/org.ow2.asm/asm-util/jars/asm-util-5.0.3.jar:/home/msoto/.ivy2/cache/com.danieltrinh/scalariform_2.10/jars/scalariform_2.10-0.1.5.jar:/home/msoto/.ivy2/cache/org.scala-lang/scalap/jars/scalap-2.10.4.jar:/home/msoto/.ivy2/cache/com.typesafe.akka/akka-actor_2.10/jars/akka-actor_2.10-2.3.8.jar:/home/msoto/.ivy2/cache/com.typesafe.akka/akka-slf4j_2.10/jars/akka-slf4j_2.10-2.3.8.jar:/home/msoto/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.2.jar:/home/msoto/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.2.jar:/home/msoto/.ivy2/cache/org.slf4j/jul-to-slf4j/jars/jul-to-slf4j-1.7.9.jar:/home/msoto/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.9.jar:/home/msoto/.ivy2/cache/org.slf4j/jcl-over-slf4j/jars/jcl-over-slf4j-1.7.9.jar:/home/msoto/.ivy2/cache/org.scala-refactoring/org.scala-refactoring.library_2.10/jars/org.scala-refactoring.library_2.10-0.6.2.jar -Xms1024m -Xmx1024m -XX:ReservedCodeCacheSize=128m -XX:MaxPermSize=256m -Densime.config=/home/msoto/Desktop/Projects/Sandbox/scala/hello/.ensime org.ensime.server.Server
```
* Press `C-c C-v z`:
```
    Error: Could not find or load main class scala.tools.nsc.MainGenericRunner

    Process ensime-inferior-scala exited abnormally with code 1
```

I just reinstalled sbt and ensime's sbt plugin, to no avail. I also tried to create a new minimal project and initialize it with sbt gen-ensime. The problem persists there.

**Comment by fommil** [comment] 2015-05-31 20:07
That needs a new ticket, it's not the same thing. Please include details of your project as described in the contributing guide.
