### ISSUE TITLE
higher order type param lost when using type alias

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#1075] opened 2015-08-27 12:59 UTC
Reported by @d6y on https://gitter.im/ensime/ensime-atom

Hover on EitherT:
<img width="424" alt="screen shot 2015-08-27 at 14 55 06" src="https://cloud.githubusercontent.com/assets/116520/9520931/a61673c6-4ccb-11e5-87cc-5c41c7b588b0.png">

Hover on Result:
<img width="372" alt="screen shot 2015-08-27 at 14 57 21" src="https://cloud.githubusercontent.com/assets/116520/9520970/f50bd098-4ccb-11e5-8661-0b9c8b2c176e.png">

```

"payload": {
    "name": "foo",
    "localName": "foo",
    "typehint": "SymbolInfo",
    "declPos": {
      "typehint": "OffsetSourcePosition",
      "file": "/Users/viktor/dev/projects/kostbevakningen/src/test/scala/se/kostbevakningen/parsers/KostbevakningenParserTest.scala",
      "offset": 1157
    },
    "type": {
      "name": "EitherT",
      "fullName": "scalaz.EitherT",
      "typehint": "BasicTypeInfo",
      "typeId": 2959,
      "typeArgs": [
        {
          "name": "String",
          "fullName": "java.lang.String",
          "typehint": "BasicTypeInfo",
          "typeId": 138,
          "typeArgs": [],
          "members": [],
          "declAs": {
            "typehint": "Class"
          }
        },
        {
          "name": "Int",
          "fullName": "scala.Int",
          "typehint": "BasicTypeInfo",
          "typeId": 675,
          "typeArgs": [],
          "members": [],
          "declAs": {
            "typehint": "Class"
          }
        }
      ],
      "members": [],
      "declAs": {
        "typehint": "Class"
      }
    },
    "isCallable": false,
    "ownerTypeId": 949
  }

```

**Comment by hedefalk** [comment] 2015-08-27 13:00
For reference, just scalaz:

```
  import scalaz._
  import Scalaz._
  import scala.concurrent._
  type Result[E, A] = EitherT[Future, E, A]
  def foo: Result[String, Int] = ???
```

**Comment by fommil** [comment] 2015-08-27 13:20
is this a dupe of #635 ?

**Comment by fommil** [comment] 2015-08-27 13:21
(if not, it's probably a bug in the presentation compiler)

**Comment by hedefalk** [comment] 2015-08-27 15:46
I'll probably install eclipse anyways for reference so i can check if the
same in scala-ide.

tor 27 aug 2015 15:21 Sam Halliday <notifications@github.com> skrev:

**Comment by hedefalk** [comment] 2015-08-27 15:51
Eclipse:

<img width="384" alt="screen shot 2015-08-27 at 17 45 52" src="https://cloud.githubusercontent.com/assets/116520/9525378/2daf78ba-4ce4-11e5-99f4-0a9c3ec02d4f.png">

**Comment by hedefalk** [comment] 2015-08-27 15:58
Idea doesn't even try :)

**Comment by fommil** [comment] 2015-08-27 16:04
ok, well if it works for `scala-ide` then it is a bug in ensime (or they have a horrible hack to workaround it that we should pinch). I suspect this is a dupe of 635 though.

**Comment by hedefalk** [comment] 2015-08-27 16:11
I think the Eclipse one is actually a lot worse. It shows a self
referencing type declaration no?

**Comment by fommil** [comment] 2015-08-27 16:45
ah! Good point

**Comment by fommil** [comment] 2016-03-31 20:23
closing as dupe, we have the backreference for when anybody wants to work on it.

**Closed by fommil** 2016-03-31 20:23 UTC
