### ISSUE TITLE
When using spray together with shapeless for routing a type mismatch is thrown

### ISSUE THREAD

**Issue by josdirksen** [ensime/ensime-server#1302] opened 2016-02-17 19:38 UTC
I'm using Ensime together with Atom, and for most cases it works great. I run, however, into an issue when working with spray. 

The following minimal code:
```
package ensime.error

import akka.actor.Actor
import spray.http.StatusCodes._
import spray.routing._

object EnsimeActor extends {
}

class EnsimeActor() extends Actor with EnsimeServer {
  def actorRefFactory = context
  def receive = runRoute(mockRoute())
}

trait EnsimeServer extends HttpService {
  val scenarioKey = "scenario"

  val mockRoute: () => Route = () => {
    (post & path("scenarios") & formField("scenarioName")) { scenario =>
      complete(OK -> s"scenario $scenario initiated")
    }
  }
}
```

Returns the following:
![image](https://cloud.githubusercontent.com/assets/1381917/13122010/37da0dfa-d5b5-11e5-9ed0-ed40aeb29cd6.png)

The strange thing is that in the initial run, the first time everything is analysed, everything goes ok. After I make a change to the file, the error pops up.  Just like the issue described in https://github.com/ensime/ensime-server/issues/1176. I also ran into that issue, but upgrading to 2.11.8-SNAPSHOT and compiling Ensime against that, solved 1176 for me as well.

Reproducing this is fairly easy, just have an sbt file like this;
```
name := "sample-project"
scalaVersion := "2.11.8-SNAPSHOT"
isSnapshot := false

// Add the versions we use of the different components here
val AkkaVersion = "2.4.1"
val ArgonautVersion = "6.1"
val JodaConvertVersion = "1.2"
val JodaTimeVersion = "2.7"
val LogbackVersion = "1.1.2"
val MockitoVersion = "1.9.5"
val ScalaCheckVersion = "1.12.1"
val ScalaTestVersion = "2.1.7"
val ScalaVersion = "2.11.6"
val SprayVersion = "1.3.3"
val WiremockVersion = "1.57"

// the resolvers that we use to get the dependencies.
resolvers ++= Seq(
  "Java.net Maven2 Repository"       at "http://download.java.net/maven/2/",
  "Sonatype releases"                at "https://oss.sonatype.org/content/repositories/releases",
  "Sonatype repo"                    at "https://oss.sonatype.org/content/groups/scala-tools/",
  "Sonatype snapshots"               at "https://oss.sonatype.org/content/repositories/snapshots",
  "Sonatype staging"                 at "http://oss.sonatype.org/content/repositories/staging",
  "Twitter Repository"               at "http://maven.twttr.com",
  "Typesafe repository releases"     at "http://repo.typesafe.com/typesafe/releases/",
  "Typesafe repository snapshots"    at "http://repo.typesafe.com/typesafe/snapshots/"
)

val librariesDeps = Seq(

  "ch.qos.logback"          %  "logback-classic"             % LogbackVersion,
  "com.typesafe.akka"      %%  "akka-actor"                  % AkkaVersion,
  "com.typesafe.akka"      %%  "akka-slf4j"                  % AkkaVersion,
  "io.spray"               %%  "spray-can"                   % SprayVersion,
  "io.spray"               %%  "spray-client"                % SprayVersion,
  "io.spray"               %%  "spray-routing-shapeless2"    % SprayVersion,
  "joda-time"               %  "joda-time"                   % JodaTimeVersion,
  "org.joda"                %  "joda-convert"                % JodaConvertVersion,
  "com.github.tomakehurst"  %  "wiremock"                    % WiremockVersion
)

val testDeps = Seq(
  "com.typesafe.akka"   %%  "akka-testkit"              % AkkaVersion          % "test",
  "io.argonaut"         %%  "argonaut"                  % ArgonautVersion      % "test",
  "io.spray"            %%  "spray-testkit"             % SprayVersion         % "test",
  "org.mockito"          %  "mockito-core"              % MockitoVersion       % "test",
  "org.scalacheck"      %%  "scalacheck"                % ScalaCheckVersion    % "test",
  "org.scalatest"       %%  "scalatest"                 % ScalaTestVersion     % "test"
)

// define all the libraries we'll use
libraryDependencies ++= librariesDeps ++ testDeps
```
And run the code pasted above.

I'd love to debug this myself, but really have no clue where to get started.

**Comment by fommil** [comment] 2016-02-17 19:46
hi @josdirksen just checking something... did you see the bug report template when you opened this ticket? I just added it and not sure if it showed up.

I think this is a dupe of https://github.com/ensime/ensime-server/issues/673

**Closed by fommil** 2016-02-17 19:46 UTC

**Comment by josdirksen** [comment] 2016-02-17 19:57
Just checked what happens when I create a new one, and indeed there was a template :). Didn't read it though when I wrote this report (my bad) and just copied over the markdown I had prepared. The issue you point to seems to describe the issue however.

**Comment by fommil** [comment] 2016-02-17 20:00
I'm just adding the troubleshooting guides to the website right this minute, so you get a free pass :stuck_out_tongue:
