### ISSUE TITLE
Show implicit conversions

### ISSUE THREAD

**Issue by koshelev** [ensime/ensime-server#955] opened 2015-05-01 20:21 UTC
It would be great to be able to view implicit conversions, similar to "Navigate" -> "Implicit Conversions" in IntelliJ and "Implicit conversion found" marker in Scala IDE

**Comment by fommil** [comment] 2015-05-02 09:23
by this, I think you're saying that you want to be able to perform some action that displays which implicits are in scope, or is this a dupe of #530

**Comment by koshelev** [comment] 2015-05-02 12:49
It would be great to have a combo from both - perform some action on an underlined block that displays implicit conversions applied to it.

**Comment by fommil** [comment] 2015-05-03 08:21
:+1:

**Comment by fommil** [comment] 2015-06-01 09:54
@edani is your latest branch looking at doing this as well?

**Comment by edani** [comment] 2015-06-01 18:13
Here's what I'm working on at the moment:
1) highlight parts of the code where implicit conversions are being applied
2) provide a command (I was going with `C-c C-v e`, same as for showing compiler errorswarnings)  that shows details on all applied conversions near the cursor

It should also be possible to jump to the definition of the implicit function  (maybe in a later PR)

As far as showing what implicit methods are in scope (not applied)  for an object, that's already possible with `C-c C-v i`. Maybe the UI could be improved.

@koshelev  Is it what you had in mind?

**Comment by fommil** [comment] 2015-06-01 18:47
that sounds utterly awesome :smile: I'll need to update the darcula theme ahead of time with the appropriate overlay name.

**Comment by koshelev** [comment] 2015-06-01 18:51
@edani it is exactly what i had in mind :) Sounds awesome!

**Comment by fommil** [comment] 2015-06-01 18:53
actually, by the sounds of it we **can** close this ticket and consider it a dupe of #530

**Closed by fommil** 2015-06-01 18:53 UTC
