### ISSUE TITLE
Presentation compiler crash on HttpServletRequest

### ISSUE THREAD

**Issue by hedefalk** [ensime/ensime-server#943] opened 2015-04-21 13:12 UTC
This should probably go to the Scala team since it's PresentationCompiler, but on one of my projects I can't typecheck. Maybe you guys can help me with it anyways.

This was the reason I once moved from Eclipse to Idea. It works find in Idea and sbt, but Eclipse and Ensime that uses PresentationCompiler, it crashes. In Ensime situation is better though. In Eclipse, every crash of the pres.compiler made me have to restart it by doing a clean. This would trigger a full rebuild with codegen and stuff which took minutes. Here I can at least continue typing :)

``` 
[Config.scala]: exception during background compile: java.lang.AssertionError: assertion failed: javax.servlet.http.HttpServletRequest
java.lang.AssertionError: assertion failed: javax.servlet.http.HttpServletRequest
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1212)
	at scala.reflect.internal.Symbols$Symbol.baseTypeSeqLength$1(Symbols.scala:1628)
	at scala.reflect.internal.Symbols$Symbol.isLess(Symbols.scala:1631)
	at scala.reflect.internal.Types$Type.baseTypeIndex(Types.scala:992)
	at scala.reflect.internal.Types$CompoundType.baseType(Types.scala:1655)
	at scala.reflect.internal.Types$ClassTypeRef$class.baseType(Types.scala:2186)
	at scala.reflect.internal.Types$TypeRef$$anon$6.baseType(Types.scala:2544)
	at scala.reflect.internal.Types$class.firstTry$1(Types.scala:6043)
	at scala.reflect.internal.Types$class.isSubType2(Types.scala:6207)
	at scala.reflect.internal.Types$class.isSubType(Types.scala:5816)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:13)
	at scala.reflect.internal.Types$class.isSubType(Types.scala:5774)
	at scala.reflect.internal.SymbolTable.isSubType(SymbolTable.scala:13)
	at scala.reflect.internal.Types$class.isWeakSubType(Types.scala:6754)
	at scala.reflect.internal.SymbolTable.isWeakSubType(SymbolTable.scala:13)
	at scala.reflect.internal.Types$Type.weak_$less$colon$less(Types.scala:914)
	at scala.tools.nsc.typechecker.Infer$Inferencer.scala$tools$nsc$typechecker$Infer$Inferencer$$isCompatible(Infer.scala:425)
	at scala.tools.nsc.typechecker.Infer$Inferencer$$anonfun$isCompatibleArgs$1.apply(Infer.scala:428)
	at scala.tools.nsc.typechecker.Infer$Inferencer$$anonfun$isCompatibleArgs$1.apply(Infer.scala:428)
	at scala.collection.LinearSeqLike$class.corresponds(LinearSeqLike.scala:76)
	at scala.collection.immutable.List.corresponds(List.scala:84)
	at scala.tools.nsc.typechecker.Infer$Inferencer.isCompatibleArgs(Infer.scala:428)
	at scala.tools.nsc.typechecker.Infer$Inferencer.typesCompatible$1(Infer.scala:814)
	at scala.tools.nsc.typechecker.Infer$Inferencer.scala$tools$nsc$typechecker$Infer$Inferencer$$isApplicable(Infer.scala:833)
	at scala.tools.nsc.typechecker.Infer$Inferencer.isApplicableSafe(Infer.scala:877)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$64.apply(Typers.scala:3148)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$64.apply(Typers.scala:3137)
	at scala.collection.TraversableLike$$anonfun$filter$1.apply(TraversableLike.scala:264)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:263)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:105)
	at scala.reflect.internal.Symbols$Symbol.filter(Symbols.scala:1667)
	at scala.tools.nsc.typechecker.Typers$Typer.preSelectOverloaded$1(Typers.scala:3137)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3165)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$92.apply(Typers.scala:4568)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$92.apply(Typers.scala:4568)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:745)
	at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4568)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4626)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4659)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5564)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5721)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedFunction(Typers.scala:2853)
	at scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:5556)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5575)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3042)
	at scala.tools.nsc.typechecker.Typers$Typer.loop$1(Typers.scala:3069)
	at scala.tools.nsc.typechecker.Typers$Typer.typedArgs(Typers.scala:3074)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$handleMonomorphicCall$1(Typers.scala:3354)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3398)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$92.apply(Typers.scala:4568)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$92.apply(Typers.scala:4568)
	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:727)
	at scala.tools.nsc.typechecker.Typers$Typer.tryTypedApply$1(Typers.scala:4568)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4626)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4659)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5564)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.typedBlock(Typers.scala:2433)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5570)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5721)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTry$1(Typers.scala:5354)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5595)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5721)
	at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5808)
	at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:834)
	at scala.tools.nsc.typechecker.Namers$Namer.methodSig(Namers.scala:1163)
	at scala.tools.nsc.typechecker.Namers$Namer.getSig$1(Namers.scala:1454)
	at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1466)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply$mcV$sp(Namers.scala:731)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:730)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1$$anonfun$apply$1.apply(Namers.scala:730)
	at scala.tools.nsc.typechecker.Namers$Namer.scala$tools$nsc$typechecker$Namers$Namer$$logAndValidate(Namers.scala:1499)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:730)
	at scala.tools.nsc.typechecker.Namers$Namer$$anonfun$monoTypeCompleter$1.apply(Namers.scala:729)
	at scala.tools.nsc.typechecker.Namers$$anon$1.completeImpl(Namers.scala:1614)
	at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter$class.complete(Namers.scala:1622)
	at scala.tools.nsc.typechecker.Namers$$anon$1.complete(Namers.scala:1612)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1231)
	at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1374)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5295)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1919)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1800)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1919)
	at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1800)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5584)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5301)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5587)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.scala$tools$nsc$typechecker$Typers$Typer$$typedStat$1(Typers.scala:2928)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer$$anonfun$61.apply(Typers.scala:3032)
	at scala.collection.immutable.List.loop$1(List.scala:170)
	at scala.collection.immutable.List.mapConserve(List.scala:186)
	at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3032)
	at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5301)
	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5587)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5642)
	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5704)
	at scala.tools.nsc.typechecker.Analyzer$typerFactory$$anon$3.apply(Analyzer.scala:99)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:464)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1173)
	at scala.tools.nsc.interactive.Global$TyperRun$$anonfun$applyPhase$1.apply(Global.scala:1173)
	at scala.reflect.internal.SymbolTable.atPhase(SymbolTable.scala:207)
	at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1173)
	at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1166)
	at scala.tools.nsc.interactive.Global.scala$tools$nsc$interactive$Global$$typeCheck(Global.scala:592)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5$$anonfun$apply$7.apply(Global.scala:508)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:504)
	at scala.tools.nsc.interactive.Global$$anonfun$backgroundCompile$5.apply(Global.scala:504)
	at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
	at scala.tools.nsc.interactive.Global.backgroundCompile(Global.scala:504)
	at scala.tools.nsc.interactive.PresentationCompilerThread.run(PresentationCompilerThread.scala:25)
[Config.scala] marking unit as crashed (crashedFiles: Set(/Users/viktor/dev/projects/uniply/src/main/scala/dfk/ka/model/Admin.scala, /Users/viktor/dev/projects/uniply/src/test/scala/dfk/ka/CirdTest.scala, /Users/viktor/dev/projects/uniply/src/main/scala/dfk/ka/config/Config.scala))

**Comment by fommil** [comment] 2015-04-21 14:45
yeah, this is typically an upstream bug so we encourage reporting there. Dupe of #673

The stacktrace isn't going to be as useful to them as a self contained example exhibiting the problem.

Personally I only see PresComp problems when using `spray-routing` or anything which makes intensive use of macros (e.g. shapeless) but your mileage may vary.

**Closed by fommil** 2015-04-21 14:45 UTC
