### ISSUE TITLE
M-x ensime fails with minimal logging

### ISSUE THREAD

**Issue by sutram** [ensime/ensime-server#859] opened 2015-03-02 04:41 UTC
HI,

I am using this with emacs 24.4.90 running on OS X Mavericks.

Ensime used to work a couple of days ago and then I upgrade Emacs to 24.4 and Ensime to the latest MELPA version and the only error I get is:

Updating ENSIME server...
Process *ensime-update* exited: exited abnormally with code 126

Any idea what is going on or a workaround to get this working again?

I deleted the Ivy cache and I made sure that plugin.sbt line points to ensime-sbt 0.1.5

**Comment by fommil** [comment] 2015-03-02 07:58
Can you see the output of the ensime update buffer?

**Comment by fommil** [comment] 2015-03-02 07:59
Workaround is always the publishLocal wind a version that worked for you : both client and server, but I suspect this is just a caching issue.

**Comment by fommil** [comment] 2015-03-02 08:11
You could also turn on emacs debug on error.

**Comment by fommil** [comment] 2015-03-02 08:12
And did you recreate your ensime config file?

**Comment by sutram** [comment] 2015-03-02 17:41
Hi, I did recreate the .ensime file and I blew away the .ensime_cache directory. The ensime update buffer has nothing in it.

This error happens immediately after hitting M-x ensime and return

I am sorry but how should I use publishLocal?

Thanks

**Comment by fommil** [comment] 2015-03-02 17:54
did you delete the `~/.emacs.d/ensime` folder as well?

You can also try `ensime-update` just to try to get that buffer to do something.

**Comment by edani** [comment] 2015-03-02 18:35
I was meaning to say something, a recent change redirects the output of the "ensime update" process to stdout.

@sutram  A workaround is to comment out this form:

```elisp
            (set-process-filter process
				;; Log output on CI testing runs.
				`(lambda (process text)
				   (when (not (null window-system))
				     (princ text 'external-debugging-output))))
```
in ensime-startup.el  and  restart emacs.

After that you can see the process' output.

**Comment by sutram** [comment] 2015-03-02 19:07
@edani Sorry, that did not work. It seems that it doesn't get very far before that error comes up. Is it possible that the .ensime file can't be parsed properly?

@fommil I deleted  ~/.emacs.d/ensime and ran M-x ensime-update. The ensime update buffer is still blank and I get the same error

**Comment by fommil** [comment] 2015-03-02 20:01
@sutram how are you generating the `.ensime`?

**Comment by sutram** [comment] 2015-03-02 22:16
@fommil "sbt gen-ensime"

I checked sbt version and it is the right version 0.13.6

**Comment by fommil** [comment] 2015-03-03 09:58
@sutram any more success?

Something else you could try is to clone the `ensime-emacs` directory and run the shell script under `test` from the top directory.

**Comment by fommil** [comment] 2015-03-03 09:59
@sutram I don't mean the version of `sbt`, I mean the version and distribution of the `sbt` script itself. Is it `paulp`'s `sbt-extras` script? (It should be)

**Comment by sutram** [comment] 2015-03-03 16:39
@fommil I cloned ensime-emacs and ran the script under the test directory. It opened up console emacs and went through and downloaded a bunch of dependencies and then bam! - the same error with an empty ensime-update buffer

I do have Paul's sbt from https://github.com/paulp/sbt-extras and I tried that and I get the same result. The version I have is 0.13.5

**Comment by sutram** [comment] 2015-03-03 17:08
Oh and when I tried to close that console mode emacs, I actually got a stack trace:

Debugger entered--Lisp error: (file-error "Opening input file" "no such file or directory" "/Users/sutram/ensime-emacs/emacs.d/ensime/classpath_2.11.5_0.9.$
  insert-file-contents("/Users/sutram/ensime-emacs/emacs.d/ensime/classpath_2.11.5_0.9.10-SNAPSHOT")
  (progn (insert-file-contents (ensime--classpath-file ensime--test-scala-version)) (let (needle) (let ((list (split-string (buffer-string) ensime--classpath-separator (qu$
  (unwind-protect (progn (insert-file-contents (ensime--classpath-file ensime--test-scala-version)) (let (needle) (let ((list (split-string (buffer-string) ensime--classpa$
  (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents (ensime--classpath-file ensime--test-scala-version)) (let (needle) (let ((list$
  (let ((temp-buffer (generate-new-buffer " *temp*"))) (save-current-buffer (set-buffer temp-buffer) (unwind-protect (progn (insert-file-contents (ensime--classpath-file e$
  ensime--extract-scala-library-jar()
  (let* ((root-dir (file-name-as-directory (make-temp-file "ensime_test_proj_" t))) (cache-dir (file-name-as-directory (concat root-dir "cache"))) (src-dir (file-name-as-d$
  ensime-create-tmp-project(((:name "test.scala" :contents "package pack.a\nclass A(value:/*1*/String){\n}")))
  (let* ((proj (ensime-create-tmp-project (list (list (quote :name) "test.scala" (quote :contents) (ensime-test-concat-lines "package pack.a" "class A(value:/*1*/String){"$
  (progn (let* ((proj (ensime-create-tmp-project (list (list (quote :name) "test.scala" (quote :contents) (ensime-test-concat-lines "package pack.a" "class A(value:/*1*/St$
  (condition-case signal (progn (let* ((proj (ensime-create-tmp-project (list (list ... "test.scala" ... ...))))) (let ((src-files (plist-get proj :src-files))) (save-curr$
  (save-excursion (condition-case signal (progn (let* ((proj (ensime-create-tmp-project (list ...)))) (let ((src-files (plist-get proj :src-files))) (save-current-buffer ($
  (lambda nil (save-excursion (condition-case signal (progn (let* ((proj (ensime-create-tmp-project ...))) (let ((src-files ...)) (save-current-buffer (set-buffer ensime-t$
  funcall((lambda nil (save-excursion (condition-case signal (progn (let* ((proj (ensime-create-tmp-project ...))) (let ((src-files ...)) (save-current-buffer (set-buffer $
  (let ((handlers (reverse (plist-get test :handlers)))) (let ((--dolist-tail-- handlers) h) (while --dolist-tail-- (setq h (car --dolist-tail--)) (setq ensime-async-handl$
  (if (plist-get test :async) (let ((handlers (reverse (plist-get test :handlers)))) (let ((--dolist-tail-- handlers) h) (while --dolist-tail-- (setq h (car --dolist-tail-$
  (let ((ensime-prefer-noninteractive t) (test (car ensime-test-queue))) (setq ensime-shared-test-state (quote nil)) (setq ensime-async-handler-stack (quote nil)) (message$
  (if ensime-test-queue (let ((ensime-prefer-noninteractive t) (test (car ensime-test-queue))) (setq ensime-shared-test-state (quote nil)) (setq ensime-async-handler-stack$
  (save-current-buffer (set-buffer ensime-testing-buffer) (if ensime-test-queue (let ((ensime-prefer-noninteractive t) (test (car ensime-test-queue))) (setq ensime-shared-$
  ensime-run-next-test()
  ensime-run-suite(((:title "Test inspect type at point." :async t :trigger (lambda nil (save-excursion (condition-case signal (progn (let* (...) (let ... ... ... ...))) ($
  ensime-run-all-tests()
  eval((ensime-run-all-tests))
  command-line-1(("--load" "test/dotemacs_test.el" "--eval" "(ensime-run-all-tests)"))
  command-line()
  normal-top-level()

**Comment by fommil** [comment] 2015-03-03 17:32
your log messages are being truncated unfortunately but in any case this is after the update script.

Right, try this, remove all the `/tmp/ensime_update_*` directories, run `update-ensime` (or the tests)... and then go into the newly created temp directory, then type `sbt saveClasspath`

**Comment by sutram** [comment] 2015-03-03 18:53
This is the top level error when I run the test:

Debugger entered--Lisp error: (file-error "Opening input file" "no such file or directory" "/Users/sutram/ensime-emacs/emacs.d/ensime/classpath_2.11.5_0.9.$
insert-file-contents("/Users/sutram/ensime-emacs/emacs.d/ensime/classpath_2.11.5_0.9.10-SNAPSHOT")

I checked /tmp and there are no files/directories with the pattern ensime_update_* and neither are they created when I run the test. Does emacs use a different tmp directory on OS X?

**Comment by fommil** [comment] 2015-03-03 20:16
possibly. Let's hack it by hand. Create a folder containing a subfolder called `project`. In the project folder, create a file called `build.properties` containing only

```
sbt.version=0.13.7
```

then create (in the top folder) a file named `build.sbt` containing this

```scala
import sbt._
import IO._
import java.io._

scalaVersion := "2.11.5"

resolvers += Resolver.sonatypeRepo("snapshots")

resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

resolvers += "Akka Repo" at "http://repo.akka.io/repository"

libraryDependencies += "org.ensime" %% "ensime" % "0.9.10-SNAPSHOT"

val saveClasspathTask = TaskKey[Unit]("saveClasspath", "Save the classpath to a file")

saveClasspathTask := {
  val managed = (managedClasspath in Runtime).value.map(_.data.getAbsolutePath)
  val unmanaged = (unmanagedClasspath in Runtime).value.map(_.data.getAbsolutePath)
  val out = file("classpath_2.11.5_0.9.10-SNAPSHOT")
  write(out, (unmanaged ++ managed).mkString(File.pathSeparator))
}
```

then type `sbt saveClasspath` and let us know what happens.

My money is still on some weird Ivy bug. You can copy the resulting classpath file into your `~/.emacs.d/ensime/` directory if it works.

**Comment by sutram** [comment] 2015-03-03 21:09
sbt saveClasspath created classpath_2.11.5_0.9.10-SNAPSHOT and it contains a bunch of jar paths in it - all from the ivy cache.

I then copied it to both the cloned ensime-emacs dir's emacs.d/ensime and the global ~/.emacs.d/ensime.

I was able to then execute test/run_emacs_tests.sh and it seems to be bringing up ensime server so at least that works.

Running M-x ensime within my project however produces the same error.

I noticed that ensime uses Scala 2.11 while my project uses Scala 2.10.4. Would that cause an issue?

**Comment by fommil** [comment] 2015-03-03 21:11
change the build.sbt to your version of ensime and run again

**Comment by sutram** [comment] 2015-03-03 21:21
To my version of Scala or Ensime?

**Comment by fommil** [comment] 2015-03-03 21:23
scala

**Comment by sutram** [comment] 2015-03-03 21:31
Ok I changed the version to 2.10.4 and ran test/run_emacs_tests.sh. This time, it tried to start the server and bailed with this exception:
Exception in thread "main" org.ensime.sexp.DeserializationException: Didn't expect a SexpNil
        at org.ensime.sexp.formats.package$.deserializationError(package.scala:5)
        at org.ensime.sexp.formats.StandardFormats$$anon$3.read(StandardFormats.scala:68)
        at org.ensime.sexp.Sexp.convertTo(Sexp.scala:18)
        at org.ensime.sexp.formats.CollectionFormats$$anon$1$$anonfun$read$1.apply(CollectionFormats.scala:63)
        at org.ensime.sexp.formats.CollectionFormats$$anon$1$$anonfun$read$1.apply(CollectionFormats.scala:63)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
        at scala.collection.immutable.List.foreach(List.scala:318)

**Comment by fommil** [comment] 2015-03-03 21:35
I meant the `sbt saveClasspath` bit.

**Comment by sutram** [comment] 2015-03-03 21:38
Yes, I did run sbt saveClasspath after changing the scala version to 2.10.4 in build.sbt. After that, I copied over the classpath file to ensime-emacs/emacs.d/ensime and got the error in my previous post

**Comment by fommil** [comment] 2015-03-03 21:41
and what about if it runs on your own project?

**Comment by fommil** [comment] 2015-03-03 21:44
ouch, I'm able to reproduce. Looks like the recent changes to `ensime-sbt` broke for the 2.10 (and probably 2.9) branches! As workaround on your project, try removing the `doc-jars` entries.

@edani is there any way we could get have the `*ensime-update*` buffer hang around incase it fails like this?

**Comment by fommil** [comment] 2015-03-03 21:56
actually, I'm not fully able to reproduce. The tests don't work but I'm able to start up ensime against a 2.10 project (actually ensime-sbt itself).

This is **really** weird.

**Comment by fommil** [comment] 2015-03-03 21:59
aha! I think I figured out why the tests are failing for 2.10. This is a totally unrelated issue.

But I have no idea why the actual server is failing to start for you. Try downloading the `ensime-sbt` git project and doing an `sbt gen-ensime` and see if you can open that up. At least we have that reference point (unless your project is OSS).

**Comment by sutram** [comment] 2015-03-03 22:05
Before I do that, would blowing away the entire ivy directory help since you mentioned that it could be a potential Ivy bug? Unfortunately my project isn't OSS.

**Comment by fommil** [comment] 2015-03-03 22:06
@sutram just move it to the side... it can take a long time to rebuild it. But yes, that's been my suspicion from the start. Ivy is a big pile of :hankey:

**Comment by fommil** [comment] 2015-03-06 19:54
did you have any joy with this? I'm closing as it seems to be a local setup issue but I'm happy to keep helping you out on this thread.

**Closed by fommil** 2015-03-06 19:54 UTC

**Comment by sutram** [comment] 2015-03-06 21:21
Unfortunately, no. I haven't had to time to debug further but will try this again over the weekend

**Comment by fommil** [comment] 2015-03-06 23:39
also check that sbt is really running from emacs. Try using `sbt-start` to confirm.

**Comment by sutram** [comment] 2015-03-07 00:55
@fommil Wow! That was it! I didn't have a shebang within the sbt script that launches sbt. It seems bash is forgiving but Emacs isn't.

I can't believe we spent so much time investigating this. Oh well. Thanks a lot for pointing me in the right direction. It was driving me crazy.

**Comment by fommil** [comment] 2015-03-07 08:36
Lol, oh well, at least it works again :-)

**Comment by fommil** [comment] 2015-03-07 08:37
Feel free to issue a PR that detects this and issues an appropriate warning

**Comment by jmglov** [comment] 2015-08-26 08:23
Thanks for this thread! I made exactly the same mistake... missing shebang. To be fair, the sbt setup instructions really should include the shebang in the script.
