### ISSUE TITLE
Ensime shows false errors in scalajs-react project

### ISSUE THREAD

**Issue by netzwerg** [ensime/ensime-server#1605] opened 2016-09-20 06:17 UTC
### Steps to reproduce

1. `git clone https://github.com/fhnw-saav/saav.git`
2. `git checkout ensime`
3. Start ensime and typecheck all files in the project

### Expected behaviour

No typecheck errors should be found

### Actual behaviour

False typecheck errors are found:

Spacemacs shows 1 error:
```
/Users/netzwerg/Projects/saav/src/main/scala/ch/fhnw/ima/saav/MainApp.scala
ERROR: japgolly.scalajs.react.extra.router.Router.type does not take parameters : line 62
```

Atom shows 31 issues (Sorry, I can't seem to copy them – where can I find a log?)

**Comment by fommil** [comment] 2016-09-22 00:31
Thanks for the repro! This is duplicate of https://github.com/ensime/ensime-server/issues/673 and we wrote pcplod to help minimise the problem if you'd be interested in investigating further @rorygraves

**Closed by fommil** 2016-09-22 00:31 UTC

**Comment by netzwerg** [comment] 2016-09-22 07:03
For the record:

Scala IDE (4.4.1-vfinal-2016-05-04T11:16:00Z-Typesafe) shows the very same error:

MainApp.java, line 62:
```
japgolly.scalajs.react.extra.router.Router.type does not take parameters
```

**Comment by fanf** [comment] 2016-09-26 08:07
For the record, it is a problem on the presentation compiler which is tracked here: https://issues.scala-lang.org/browse/SI-9716

Feel free to vote on the issue to raise its awareness from Lightbent.

**Comment by fommil** [comment] 2016-09-26 13:56
They don't work that way. They are over burdened and only respond to cash. If you'd be interested in digging into fixing this yourself, we created pcplod for reproductions, then you can dig into it.
