### ISSUE TITLE
Hang when looking up definition

### ISSUE THREAD

**Issue by raboof** [ensime/ensime-server#983] opened 2015-06-09 10:14 UTC
Running ensime in Emacs, sometimes when I want to view the definition of a trait, Emacs hangs.

I've been able to (so far) reliably reproduce this by ctrl-clicking `MatcherWords` when viewing `org.scalatest.Matchers`.

Emacs becomes unresponsive (the mouse cursor changes to an indicator and the window doesn't accept new input).

I'm new to Emacs and Ensime, so I'd appreciate any help in further tracking down this problem.

**Comment by fommil** [comment] 2015-06-09 13:12
Yup, it's a known performance regression. Dupe of #780

**Comment by fommil** [comment] 2015-06-09 13:13
Sorry #970

**Closed by fommil** 2015-06-09 13:12 UTC

**Comment by raboof** [comment] 2015-06-09 13:29
OK, sorry for the duplicate

**Comment by fommil** [comment] 2015-06-09 17:45
that's ok, it's relatively new and I hadn't flagged it as a FAQ
