### ISSUE TITLE
Inform the user about existential types.

### ISSUE THREAD

**Issue by asznajder** [ensime/ensime-server#1369] opened 2016-03-30 17:57 UTC
When an user does something with an existentially quantified type, then we should inform about this. Currently this information is erased, but it would be great to notify the user about this. Existential type information is erased currently in `TypeInfo` object's `apply` method. 

Type information is generated for example as a result of `askInspectTypeAt` method in `RichCompilerControl` that's called when `Analyzer` receives `InspectTypeAtPointReq`.

**Comment by fommil** [comment] 2016-03-30 18:47
This might be a dupe, search for refined types, maybe.

**Comment by fommil** [comment] 2016-03-31 21:56
dupe of #635

**Closed by fommil** 2016-03-31 21:56 UTC
